extern int diffusion_run_wrapper(
    double *w, int w_size_0, int w_size_1, double *vn, int vn_size_0,
    int vn_size_1, double *exner, int exner_size_0, int exner_size_1,
    double *theta_v, int theta_v_size_0, int theta_v_size_1, double *rho,
    int rho_size_0, int rho_size_1, double *hdef_ic, int hdef_ic_size_0,
    int hdef_ic_size_1, double *div_ic, int div_ic_size_0, int div_ic_size_1,
    double *dwdx, int dwdx_size_0, int dwdx_size_1, double *dwdy,
    int dwdy_size_0, int dwdy_size_1, double dtime, int linit, int on_gpu);
extern int diffusion_init_wrapper(
    double *vct_a, int vct_a_size_0, double *vct_b, int vct_b_size_0,
    double *theta_ref_mc, int theta_ref_mc_size_0, int theta_ref_mc_size_1,
    double *wgtfac_c, int wgtfac_c_size_0, int wgtfac_c_size_1,
    double *e_bln_c_s, int e_bln_c_s_size_0, int e_bln_c_s_size_1,
    double *geofac_div, int geofac_div_size_0, int geofac_div_size_1,
    double *geofac_grg_x, int geofac_grg_x_size_0, int geofac_grg_x_size_1,
    double *geofac_grg_y, int geofac_grg_y_size_0, int geofac_grg_y_size_1,
    double *geofac_n2s, int geofac_n2s_size_0, int geofac_n2s_size_1,
    double *nudgecoeff_e, int nudgecoeff_e_size_0, double *rbf_coeff_1,
    int rbf_coeff_1_size_0, int rbf_coeff_1_size_1, double *rbf_coeff_2,
    int rbf_coeff_2_size_0, int rbf_coeff_2_size_1, int *mask_hdiff,
    int mask_hdiff_size_0, int mask_hdiff_size_1, double *zd_diffcoef,
    int zd_diffcoef_size_0, int zd_diffcoef_size_1, int *zd_vertoffset,
    int zd_vertoffset_size_0, int zd_vertoffset_size_1,
    int zd_vertoffset_size_2, double *zd_intcoef, int zd_intcoef_size_0,
    int zd_intcoef_size_1, int zd_intcoef_size_2, int ndyn_substeps,
    double rayleigh_damping_height, int nflat_gradp, int diffusion_type,
    int hdiff_w, int hdiff_vn, int zdiffu_t, int type_t_diffu,
    int type_vn_diffu, double hdiff_efdt_ratio,
    double smagorinski_scaling_factor, int hdiff_temp, double thslp_zdiffu,
    double thhgtd_zdiffu, double denom_diffu_v, double nudge_max_coeff,
    int itype_sher, int ltkeshs, double lowest_layer_thickness,
    double model_top_height, double stretch_factor, int backend, int on_gpu);
