# Only the '/workspace' folder is preserved on restarts, therefore both
# Python packages and pre-commit caches need to be installed there
# except pre-commit which doesn't work with PIP_USER=yes (therefore the alias)
image:
  file: .gitpod.Dockerfile
tasks:
- name: Setup venv and dev tools
  init: |
    mkdir .vscode
    cp .gitpod/.vscode/* .vscode/
    pip install --upgrade pip setuptools wheel
    pip install -r requirements-dev.txt
    pre-commit install --install-hooks
  #command: alias pre-commit="PIP_USER=no pre-commit"
  env:
    PIP_SRC: _external_src
    PRE_COMMIT_HOME: /workspace/.caches/pre-commit
vscode:
    extensions:
        - ms-python.python
        - ms-toolsai.jupyter
        - ms-toolsai.jupyter-keymap
        - ms-toolsai.jupyter-renderers
        - genuitecllc.codetogether

