export CC="$(which gcc)"
export MPICH_CC="$(which gcc)"
export CXX="$(which g++)"
export MPICH_CXX="$(which g++)"
export HUGETLB_ELFMAP="no"
export HUGETLB_MORECORE="no"
export PYTHONOPTIMIZE="2"
export CUPY_INSTALL_USE_HIP="1"
export HCC_AMDGPU_TARGET="gfx942"
export ROCM_HOME="/user-environment/env/default"
export HIPCC=$(which hipcc)
export ROCM_VERSION="7.1.0"
# export LLVMAMD_HASH="5irafh2pqa7kbe3z7mdvot6rdu63qmj6"
# export HIP_CLANG_PATH=/user-environment/linux-zen3/llvm-amdgpu-${ROCM_VERSION}-${LLVMAMD_HASH}/bin
# export DEVICE_LIB_PATH=/user-environment/linux-zen3/llvm-amdgpu-${ROCM_VERSION}-${LLVMAMD_HASH}/amdgcn/bitcode
# export LD_LIBRARY_PATH=/user-environment/linux-zen3/llvm-amdgpu-${ROCM_VERSION}-${LLVMAMD_HASH}/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/user-environment/linux-zen3/rocprofiler-dev-7.1.0-i7wbbbgrx7jjp4o2xroyj5j263dkzplv/lib:$LD_LIBRARY_PATH
# export PATH=/user-environment/linux-zen3/llvm-amdgpu-${ROCM_VERSION}-${LLVMAMD_HASH}/bin:$PATH
export LD_PRELOAD=/user-environment/env/default/lib/libomp.so:$LD_PRELOAD
# export LD_LIBRARY_PATH=/capstor/scratch/cscs/ioannmag/beverin/cycle33/ICON4PY/rocprof-trace-decoder-manylinux-2.28-0.1.6-Linux:$LD_LIBRARY_PATH # TODO(iomaganaris): fix that
# export LD_LIBRARY_PATH=/user-environment/env/default/lib:/user-environment/env/default/lib:$LD_LIBRARY_PATH 

# export GT4PY_UNSTRUCTURED_HORIZONTAL_HAS_UNIT_STRIDE="1"
# export GT4PY_BUILD_CACHE_LIFETIME=persistent
# export GT4PY_BUILD_CACHE_DIR=dycore_710_040226_granule_new
# # export GT4PY_COLLECT_METRICS_LEVEL=10
# export GT4PY_ADD_GPU_TRACE_MARKERS="1"
# export ICON4PY_STENCIL_TEST_WARMUP_ROUNDS=3
# export ICON4PY_STENCIL_TEST_ITERATIONS=10
# export ICON4PY_STENCIL_TEST_BENCHMARK_ROUNDS=10
# # export ROCPROF=rocprofv2
# export HIPFLAGS="-std=c++17 -fPIC -O3 -march=native -Wno-unused-parameter -save-temps -Rpass-analysis=kernel-resource-usage"