exact = true
exclude = []
forbid_circular_dependencies = true
interfaces = []
source_roots = [
    "model/atmosphere/advection/src",
    "model/atmosphere/diffusion/src",
    "model/atmosphere/dycore/src",
    "model/atmosphere/subgrid_scale_physics/microphysics/src",
    "model/common/src",
    "model/driver/src",
    "model/testing/src",
    "tools/src",
]

[[modules]]
path = "icon4py.model.atmosphere.advection"
depends_on = [
    { path = "icon4py.model.common" },
]

[[modules]]
path = "icon4py.model.atmosphere.diffusion"
depends_on = [
    { path = "icon4py.model.common" },
]

[[modules]]
path = "icon4py.model.atmosphere.dycore"
depends_on = [
    { path = "icon4py.model.common" },
]

[[modules]]
path = "icon4py.model.atmosphere.subgrid_scale_physics.microphysics"
depends_on = [
    { path = "icon4py.model.common" },
]

[[modules]]
path = "icon4py.model.common"
depends_on = []

[[modules]]
path = "icon4py.model.driver"
depends_on = [
    { path = "icon4py.model.atmosphere.diffusion" },
    { path = "icon4py.model.atmosphere.dycore" },
    { path = "icon4py.model.common" },
    { path = "icon4py.model.testing" },  # TODO: remove this dependency when driver is fully standalone
]

[[modules]]
path = "icon4py.model.testing"
depends_on = [
    { path = "icon4py.model.common" },
]

[[modules]]
path = "icon4py.tools"
depends_on = []

[[modules]]
path = "icon4py.tools.common"
depends_on = [
    { path = "icon4py.model.common" },
]

[[modules]]
path = "icon4py.tools.f2ser"
depends_on = [
    { path = "icon4py.tools.liskov" },
]

[[modules]]
path = "icon4py.tools.icon4pygen"
depends_on = [
    { path = "icon4py.model.common" },
    { path = "icon4py.tools.common" },
]

[[modules]]
path = "icon4py.tools.liskov"
depends_on = [
    { path = "icon4py.tools" },
    { path = "icon4py.tools.common" },
]

[[modules]]
path = "icon4py.tools.py2fgen"
depends_on = [
    { path = "icon4py.model.atmosphere.diffusion" },
    { path = "icon4py.model.atmosphere.dycore" },
    { path = "icon4py.model.common" },
    { path = "icon4py.tools.common" },
    { path = "icon4py.tools.icon4pygen" },
]
