# ICON4Py - ICON inspired code in Python and GT4Py
#
# Copyright (c) 2022-2024, ETH Zurich and MeteoSwiss
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause
import logging
import pathlib
from typing import Annotated

import typer

from icon4py.model.common import model_backends
from icon4py.model.common.decomposition import definitions as decomp_defs
from icon4py.model.standalone_driver import driver_states, driver_utils, standalone_driver
from icon4py.model.standalone_driver.testcases import initial_condition


log = logging.getLogger(__name__)


def main(
    *,
    grid_file_path: pathlib.Path,
    icon4py_backend: str | model_backends.BackendLike,
    output_path: pathlib.Path,
    log_level: str,
    print_distributed_debug_msg: bool,
    force_serial_run: bool,
    enable_output: bool,
) -> tuple[driver_states.DriverStates, decomp_defs.DecompositionInfo]:
    """
    This is a function that runs the icon4py driver from a grid file with the initial
    condition from the Jablonowski Williamson test case

    An Icon4pyDriver object is generated by calling the initialize_driver function
    The initial condition is generated from the model_initialization_jabw function

    The integration can then be executed by calling time_integration function in Icon4pyDriver

    Programmatic entry point: accepts either a backend name (str) or a BackendLike
    object. All arguments are required; the defaults live in the command line
    interface, :func:`cli`.
    """

    backend_like = driver_utils.get_backend_from_name(icon4py_backend)

    icon4py_driver: standalone_driver.Icon4pyDriver = standalone_driver.initialize_driver(
        output_path=output_path,
        grid_file_path=grid_file_path,
        log_level=log_level,
        print_distributed_debug_msg=print_distributed_debug_msg,
        backend_like=backend_like,
        force_serial_run=force_serial_run,
        enable_output=enable_output,
    )

    log.info("Generating the initial condition")
    ds: driver_states.DriverStates = initial_condition.jablonowski_williamson(
        grid=icon4py_driver.grid,
        geometry_field_source=icon4py_driver.static_field_factories.geometry_field_source,
        interpolation_field_source=icon4py_driver.static_field_factories.interpolation_field_source,
        metrics_field_source=icon4py_driver.static_field_factories.metrics_field_source,
        backend=icon4py_driver.backend,
        lowest_layer_thickness=icon4py_driver.vertical_grid_config.lowest_layer_thickness,
        model_top_height=icon4py_driver.vertical_grid_config.model_top_height,
        stretch_factor=icon4py_driver.vertical_grid_config.stretch_factor,
        damping_height=icon4py_driver.vertical_grid_config.rayleigh_damping_height,
        exchange=icon4py_driver.exchange,
    )

    log.info("driver setup: DONE")
    log.info("time loop: START")

    icon4py_driver.time_integration(
        ds,
        do_prep_adv=False,
    )

    log.info("time loop:  DONE")
    return ds, icon4py_driver.decomposition_info


app = typer.Typer()


@app.command()
def cli(
    *,
    grid_file_path: Annotated[pathlib.Path, typer.Option(help="Grid file path.")],
    # it may be better to split device from backend,
    # or only asking for cpu or gpu and the best backend for perfornamce is handled inside icon4py,
    # whether to automatically use gpu if cupy is installed can be discussed further
    icon4py_backend: Annotated[
        str,
        typer.Option(
            help=f"GT4Py backend for running the entire driver. Possible options are: {' / '.join([*model_backends.BACKENDS.keys()])}",
        ),
    ],
    output_path: Annotated[
        pathlib.Path, typer.Option(help="Folder path that holds the output and log files.")
    ] = pathlib.Path("./output"),
    log_level: Annotated[
        str,
        typer.Option(
            help=f"Logging level of the model. Possible options are {' / '.join([*driver_utils._LOGGING_LEVELS.keys()])}",
        ),
    ] = next(iter(driver_utils._LOGGING_LEVELS.keys())),
    print_distributed_debug_msg: Annotated[
        bool,
        typer.Option(
            help="Print out debug logging message for all ranks (only works when log_level is set to debug).",
        ),
    ] = False,
    force_serial_run: Annotated[
        bool,
        typer.Option(
            help="Force a single-node run even if MPI is available. Useful to build serial reference output within MPI test sessions.",
        ),
    ] = False,
    enable_output: Annotated[
        bool,
        typer.Option(
            "--enable-output/--no-enable-output",
            help=(
                "Write the prognostic (rho, exner, theta_v, w, vn) and diagnostic "
                "(u, v, temperature, virtual temperature, pressure) fields to a single "
                "NETCDF/UGRID output file (single node). Enabled by default; "
                "use --no-enable-output to run without output."
            ),
        ),
    ] = True,
) -> None:
    """Command-line entry point wrapping :func:`main`.

    Kept separate from :func:`main` because Typer cannot parse the
    `str | BackendLike` Union accepted by the programmatic API: the CLI only takes a
    backend name, while tests and other callers can pass backend objects to `main`
    directly.
    """
    main(
        grid_file_path=grid_file_path,
        icon4py_backend=icon4py_backend,
        output_path=output_path,
        log_level=log_level,
        print_distributed_debug_msg=print_distributed_debug_msg,
        force_serial_run=force_serial_run,
        enable_output=enable_output,
    )


if __name__ == "__main__":
    app()
