# ICON4Py - ICON inspired code in Python and GT4Py
#
# Copyright (c) 2022-2024, ETH Zurich and MeteoSwiss
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause
import logging
import pathlib
from typing import Annotated

import devtools
import typer

from icon4py.model.common import model_backends
from icon4py.model.common.decomposition import definitions as decomp_defs
from icon4py.model.standalone_driver import driver_states, driver_utils, standalone_driver
from icon4py.model.standalone_driver.testcases import initial_condition


log = logging.getLogger(__name__)


def _dump_init_fields(
    driver: standalone_driver.Icon4pyDriver,
    ds: driver_states.DriverStates,
    output_path: pathlib.Path,
) -> None:
    """Dump initial prognostic and diagnostic fields with global indices for reproducibility verification."""
    import pickle

    import numpy as np

    def _to_numpy(arr):
        """Convert array to NumPy, handling CuPy arrays."""
        return arr.get() if hasattr(arr, "get") else np.asarray(arr)

    rank = driver.processor_props.rank
    decomp_info = driver.decomposition_info
    from icon4py.model.common import dimension as dims

    cell_gidx = decomp_info.global_index(dims.CellDim)
    edge_gidx = decomp_info.global_index(dims.EdgeDim)

    prog = ds.prognostics.current
    diag = ds.diagnostic
    data = {
        "cell_global_index": _to_numpy(cell_gidx),
        "edge_global_index": _to_numpy(edge_gidx),
        "rho": _to_numpy(prog.rho.ndarray),
        "theta_v": _to_numpy(prog.theta_v.ndarray),
        "exner": _to_numpy(prog.exner.ndarray),
        "w": _to_numpy(prog.w.ndarray),
        "vn": _to_numpy(prog.vn.ndarray),
        "u": _to_numpy(diag.u.ndarray),
        "v": _to_numpy(diag.v.ndarray),
    }
    output_path.mkdir(parents=True, exist_ok=True)
    out_file = output_path / f"init_fields_rank{rank}.pkl"
    with open(out_file, "wb") as f:
        pickle.dump(data, f)
    log.warning(f"Dumped init fields to {out_file}")


def main(
    grid_file_path: Annotated[pathlib.Path, typer.Option(help="Grid file path.")],
    # it may be better to split device from backend,
    # or only asking for cpu or gpu and the best backend for perfornamce is handled inside icon4py,
    # whether to automatically use gpu if cupy is installed can be discussed further
    icon4py_backend: Annotated[
        str,
        typer.Option(
            help=f"GT4Py backend for running the entire driver. Possible options are: {' / '.join([*model_backends.BACKENDS.keys()])}",
        ),
    ],
    output_path: Annotated[
        pathlib.Path, typer.Option(help="Folder path that holds the output and log files.")
    ] = pathlib.Path("./output"),
    log_level: Annotated[
        str,
        typer.Option(
            help=f"Logging level of the model. Possible options are {' / '.join([*driver_utils._LOGGING_LEVELS.keys()])}",
        ),
    ] = next(iter(driver_utils._LOGGING_LEVELS.keys())),
    output_frequency: Annotated[
        str,
        typer.Option(
            help="Diagnostic output frequency. Options: none / hourly / daily / final.",
        ),
    ] = "none",
    force_serial_run: Annotated[
        bool,
        typer.Option(
            help="Force a single-node run even if MPI is available. Useful to build serial reference output within MPI test sessions.",
        ),
    ] = False,
    dtime: Annotated[
        float,
        typer.Option(
            help="Time step size in seconds (default per resolution: r2b6=75, r2b7=40, r2b8=20, r2b9=10, r2b10=5).",
        ),
    ] = 10.0,
    reproducible_reductions: Annotated[
        bool,
        typer.Option(
            help="Use reproducible global reductions (gather-and-sort) to produce bitwise-identical results across different MPI rank counts.",
        ),
    ] = False,
    dump_init_fields: Annotated[
        bool,
        typer.Option(
            help="Dump initial prognostic fields per rank for reproducibility verification.",
        ),
    ] = False,
) -> tuple[driver_states.DriverStates, decomp_defs.DecompositionInfo]:
    """
    This is a function that runs the icon4py driver from a grid file with the initial
    condition from the Jablonowski Williamson test case

    An Icon4pyDriver object is generated by calling the initialize_driver function
    The initial condition is generated from the model_initialization_jabw function

    The integration can then be executed by calling time_integration function in Icon4pyDriver
    """

    timer_total = devtools.Timer(driver_states.DriverTimers.TOTAL.value, dp=6, verbose=False)
    timer_init = devtools.Timer(driver_states.DriverTimers.INIT.value, dp=6, verbose=False)

    with timer_total:
        with timer_init:
            icon4py_driver: standalone_driver.Icon4pyDriver = standalone_driver.initialize_driver(
                output_path=output_path,
                grid_file_path=grid_file_path,
                log_level=log_level,
                backend_name=icon4py_backend,
                force_serial_run=force_serial_run,
                dtime=dtime,
                reproducible_reductions=reproducible_reductions,
            )

            log.info("Generating the initial condition")
            ds: driver_states.DriverStates = initial_condition.jablonowski_williamson(
                grid=icon4py_driver.grid,
                geometry_field_source=icon4py_driver.static_field_factories.geometry_field_source,
                interpolation_field_source=icon4py_driver.static_field_factories.interpolation_field_source,
                metrics_field_source=icon4py_driver.static_field_factories.metrics_field_source,
                backend=icon4py_driver.backend,
                lowest_layer_thickness=icon4py_driver.vertical_grid_config.lowest_layer_thickness,
                model_top_height=icon4py_driver.vertical_grid_config.model_top_height,
                stretch_factor=icon4py_driver.vertical_grid_config.stretch_factor,
                damping_height=icon4py_driver.vertical_grid_config.rayleigh_damping_height,
                exchange=icon4py_driver.exchange,
            )

        if dump_init_fields:
            _dump_init_fields(icon4py_driver, ds, output_path=icon4py_driver.config.output_path)

        log.info("driver setup: DONE")
        log.info("time loop: START")

        # Attach the init and total timers so they appear in the timer report
        icon4py_driver.timer_collection.timers[driver_states.DriverTimers.TOTAL.value] = timer_total
        icon4py_driver.timer_collection.timers[driver_states.DriverTimers.INIT.value] = timer_init

        icon4py_driver.time_integration(
            ds,
            do_prep_adv=False,
            output_frequency=driver_states.OutputFrequency(output_frequency),
        )

    log.info("time loop:  DONE")
    return ds, icon4py_driver.decomposition_info


if __name__ == "__main__":
    typer.run(main)
