# ICON4Py - ICON inspired code in Python and GT4Py
#
# Copyright (c) 2022-2024, ETH Zurich and MeteoSwiss
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause
import logging
import pathlib
from typing import Annotated

import typer

from icon4py.model.common import model_backends
from icon4py.model.standalone_driver import driver_states, driver_utils, standalone_driver
from icon4py.model.standalone_driver.testcases import initial_condition


log = logging.getLogger(__name__)


def main(
    configuration_file_path: Annotated[
        pathlib.Path, typer.Argument(help="Configuration file path.")
    ],
    grid_file_path: Annotated[pathlib.Path, typer.Option(help="Grid file path.")],
    # it may be better to split device from backend,
    # or only asking for cpu or gpu and the best backend for perfornamce is handled inside icon4py,
    # whether to automatically use gpu if cupy is installed can be discussed further
    icon4py_backend: Annotated[
        str,
        typer.Option(
            help=f"GT4Py backend for running the entire driver. Possible options are: {' / '.join([*model_backends.BACKENDS.keys()])}",
        ),
    ],
    output_path: Annotated[
        pathlib.Path, typer.Option(help="Folder path that holds the output and log files.")
    ] = pathlib.Path("./output"),
    log_level: Annotated[
        str,
        typer.Option(
            help=f"Logging level of the model. Possible options are {' / '.join([*driver_utils._LOGGING_LEVELS.keys()])}",
        ),
    ] = next(iter(driver_utils._LOGGING_LEVELS.keys())),
) -> None:
    """
    This is a function that runs the icon4py driver from a grid file with the initial
    condition from the Jablonowski Williamson test case

    An Icon4pyDriver object is generated by calling the initialize_driver function
    The initial condition is generated from the model_initialization_jabw function

    The integration can then be executed by calling time_integration function in Icon4pyDriver
    """

    icon4py_driver: standalone_driver.Icon4pyDriver = standalone_driver.initialize_driver(
        configuration_file_path=configuration_file_path,
        output_path=output_path,
        grid_file_path=grid_file_path,
        log_level=log_level,
        backend_name=icon4py_backend,
    )

    log.info("Generating the initial condition")
    ds: driver_states.DriverStates = initial_condition.jablonowski_williamson(
        grid=icon4py_driver.grid,
        geometry_field_source=icon4py_driver.static_field_factories.geometry_field_source,
        interpolation_field_source=icon4py_driver.static_field_factories.interpolation_field_source,
        metrics_field_source=icon4py_driver.static_field_factories.metrics_field_source,
        backend=icon4py_driver.backend,
    )

    log.info("driver setup: DONE")
    log.info("time loop: START")

    icon4py_driver.time_integration(
        ds,
        do_prep_adv=False,
    )

    log.info("time loop:  DONE")


if __name__ == "__main__":
    typer.run(main)
