# ICON4Py - ICON inspired code in Python and GT4Py
#
# Copyright (c) 2022-2024, ETH Zurich and MeteoSwiss
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause

import logging
import pathlib
from typing import Annotated

import typer

from icon4py.model.common import model_backends
from icon4py.model.standalone_driver import driver_states, driver_utils, standalone_driver
from icon4py.model.standalone_driver.testcases import jablonowski_williamson


log = logging.getLogger(__name__)


def run_icon4py_driver(
    configuration_file_path: Annotated[str, typer.Argument(help="Configuration file path.")],
    grid_file_path: Annotated[str, typer.Option(help="Grid file path.")],
    icon4py_backend: Annotated[
        str,
        typer.Option(
            help=f"GT4Py backend for running the entire driver. Possible options are: {' / '.join([*model_backends.ICON4PY_BACKENDS.keys()])}",
        ),
    ],
    output_path: Annotated[
        str, typer.Option(help="Folder path that holds the output and log files.")
    ] = "./output",
    log_level: Annotated[
        str,
        typer.Option(
            help=f"Logging level of log files. Possible options are {' / '.join([*driver_utils._LOGGING_LEVELS.keys()])}",
        ),
    ] = next(iter(driver_utils._LOGGING_LEVELS.keys())),
) -> None:
    """
    This is a function that runs the icon4py driver from a grid file with the initial
    condition from the Jablonowski Williamson test case

    An Icon4pyDriver object is generated by calling the initialize_driver function
    The initial condition is generated from the model_initialization_jabw function

    The integration can then be executed by calling time_integration function in Icon4pyDriver
    """

    backend = driver_utils.get_backend_from_name(icon4py_backend)
    absolute_output_path = pathlib.Path(output_path).absolute()
    absolute_output_path.mkdir(parents=True, exist_ok=False)

    icon4py_driver: standalone_driver.Icon4pyDriver
    icon4py_driver = standalone_driver.initialize_driver(
        configuration_file_path=pathlib.Path(configuration_file_path).absolute(),
        output_path=absolute_output_path,
        grid_file_path=pathlib.Path(grid_file_path).absolute(),
        log_level=log_level,
        backend=backend,
    )

    log.info("Generating the initial condition")
    ds: driver_states.DriverStates
    ds = jablonowski_williamson.model_initialization_jabw(
        grid=icon4py_driver.grid_manager.grid,
        geometry_field_source=icon4py_driver.static_field_factories.geometry_field_source,
        interpolation_field_source=icon4py_driver.static_field_factories.interpolation_field_source,
        metrics_field_source=icon4py_driver.static_field_factories.metrics_field_source,
        backend=backend,
    )

    log.info("driver setup: DONE")
    log.info("time loop: START")

    icon4py_driver.time_integration(
        ds.diffusion_diagnostic,
        ds.solve_nonhydro_diagnostic,
        ds.prognostics,
        ds.prep_advection_prognostic,
        do_prep_adv=False,
    )

    log.info("time loop:  DONE")


if __name__ == "__main__":
    typer.run(run_icon4py_driver)
