extern int grid_init_wrapper(
    int *cell_starts, int cell_starts_size_0, int *cell_ends,
    int cell_ends_size_0, int *vertex_starts, int vertex_starts_size_0,
    int *vertex_ends, int vertex_ends_size_0, int *edge_starts,
    int edge_starts_size_0, int *edge_ends, int edge_ends_size_0, int *c2e,
    int c2e_size_0, int c2e_size_1, int *e2c, int e2c_size_0, int e2c_size_1,
    int *c2e2c, int c2e2c_size_0, int c2e2c_size_1, int *e2c2e,
    int e2c2e_size_0, int e2c2e_size_1, int *e2v, int e2v_size_0,
    int e2v_size_1, int *v2e, int v2e_size_0, int v2e_size_1, int *v2c,
    int v2c_size_0, int v2c_size_1, int *e2c2v, int e2c2v_size_0,
    int e2c2v_size_1, int *c2v, int c2v_size_0, int c2v_size_1,
    int *c_owner_mask, int c_owner_mask_size_0, int *e_owner_mask,
    int e_owner_mask_size_0, int *v_owner_mask, int v_owner_mask_size_0,
    int *c_glb_index, int c_glb_index_size_0, int *e_glb_index,
    int e_glb_index_size_0, int *v_glb_index, int v_glb_index_size_0,
    double *tangent_orientation, int tangent_orientation_size_0,
    double *inverse_primal_edge_lengths, int inverse_primal_edge_lengths_size_0,
    double *inv_dual_edge_length, int inv_dual_edge_length_size_0,
    double *inv_vert_vert_length, int inv_vert_vert_length_size_0,
    double *edge_areas, int edge_areas_size_0, double *f_e, int f_e_size_0,
    double *cell_center_lat, int cell_center_lat_size_0,
    double *cell_center_lon, int cell_center_lon_size_0, double *cell_areas,
    int cell_areas_size_0, double *primal_normal_vert_x,
    int primal_normal_vert_x_size_0, int primal_normal_vert_x_size_1,
    double *primal_normal_vert_y, int primal_normal_vert_y_size_0,
    int primal_normal_vert_y_size_1, double *dual_normal_vert_x,
    int dual_normal_vert_x_size_0, int dual_normal_vert_x_size_1,
    double *dual_normal_vert_y, int dual_normal_vert_y_size_0,
    int dual_normal_vert_y_size_1, double *primal_normal_cell_x,
    int primal_normal_cell_x_size_0, int primal_normal_cell_x_size_1,
    double *primal_normal_cell_y, int primal_normal_cell_y_size_0,
    int primal_normal_cell_y_size_1, double *dual_normal_cell_x,
    int dual_normal_cell_x_size_0, int dual_normal_cell_x_size_1,
    double *dual_normal_cell_y, int dual_normal_cell_y_size_0,
    int dual_normal_cell_y_size_1, double *edge_center_lat,
    int edge_center_lat_size_0, double *edge_center_lon,
    int edge_center_lon_size_0, double *primal_normal_x,
    int primal_normal_x_size_0, double *primal_normal_y,
    int primal_normal_y_size_0, double mean_cell_area, int comm_id,
    int num_vertices, int num_cells, int num_edges, int vertical_size,
    int limited_area, int backend, int on_gpu);