# ICON4Py - ICON inspired code in Python and GT4Py
#
# Copyright (c) 2022-2024, ETH Zurich and MeteoSwiss
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause

"""
The quantities of the model, one type-level tag per quantity at one place on the grid.

The tags are named `<Quantity>On<Place>`, as icon4py names its fields
(`theta_v_at_cells_on_half_levels`). The CF attributes are those of the tables in
`icon4py.model.common.states.data`; a quantity without a CF name has `standard_name=None`
and a `long_name` from the docstring of the field it replaces.
"""

from icon4py.model.common import dimension as dims
from icon4py.model.common.components.framework import Quantity, Tendency


CELL = (dims.CellDim,)
CELL_K = (dims.CellDim, dims.KDim)
CELL_KHALF = (dims.CellDim, dims.KHalfDim)
EDGE_K = (dims.EdgeDim, dims.KDim)
EDGE_KHALF = (dims.EdgeDim, dims.KHalfDim)

# fmt: off

# --- prognostics ---

class RhoOnCellK(Quantity, dims=CELL_K, standard_name="air_density", long_name="density", units="kg m-3"): ...
class RhoOnCellKHalf(Quantity, dims=CELL_KHALF, standard_name="air_density", long_name="density at half levels", units="kg m-3"): ...
class WOnCellKHalf(Quantity, dims=CELL_KHALF, standard_name="upward_air_velocity", long_name="vertical air velocity component", units="m s-1"): ...
class VnOnEdgeK(Quantity, dims=EDGE_K, standard_name="normal_velocity", long_name="velocity normal to edge", units="m s-1"): ...
class VnOnEdgeKHalf(Quantity, dims=EDGE_KHALF, standard_name="normal_velocity", long_name="velocity normal to edge at half levels", units="m s-1", precision="vp"): ...
class TangentialWindOnEdgeK(Quantity, dims=EDGE_K, standard_name="tangential_velocity", long_name="velocity tangential to edge", units="m s-1", precision="vp"): ...
class ExnerOnCellK(Quantity, dims=CELL_K, standard_name="dimensionless_exner_function", long_name="exner function", units="1"): ...
class ThetaVOnCellK(Quantity, dims=CELL_K, standard_name="virtual_potential_temperature", long_name="virtual potential temperature", units="K"): ...
class ThetaVOnCellKHalf(Quantity, dims=CELL_KHALF, standard_name="virtual_potential_temperature", long_name="virtual potential temperature at half levels", units="K"): ...

# --- tracers ---

class QvOnCellK(Quantity, dims=CELL_K, standard_name="specific_humidity", long_name="ratio of water vapor mass to total moist air parcel mass", units="1"): ...
class QcOnCellK(Quantity, dims=CELL_K, standard_name="specific_cloud_content", long_name="ratio of cloud water mass to total moist air parcel mass", units="1"): ...
class QiOnCellK(Quantity, dims=CELL_K, standard_name="specific_ice_content", long_name="ratio of cloud ice mass to total moist air parcel mass", units="1"): ...
class QrOnCellK(Quantity, dims=CELL_K, standard_name="specific_rain_content", long_name="ratio of rain mass to total moist air parcel mass", units="1"): ...
class QsOnCellK(Quantity, dims=CELL_K, standard_name="specific_snow_content", long_name="ratio of snow mass to total moist air parcel mass", units="1"): ...
class QgOnCellK(Quantity, dims=CELL_K, standard_name="specific_graupel_content", long_name="ratio of graupel mass to total moist air parcel mass", units="1"): ...

# --- diagnostics ---

class UOnCellK(Quantity, dims=CELL_K, standard_name="eastward_wind", long_name="eastward wind component", units="m s-1"): ...
class VOnCellK(Quantity, dims=CELL_K, standard_name="northward_wind", long_name="northward wind component", units="m s-1"): ...
class TemperatureOnCellK(Quantity, dims=CELL_K, standard_name="air_temperature", long_name="air temperature", units="K"): ...
class VirtualTemperatureOnCellK(Quantity, dims=CELL_K, standard_name="air_virtual_temperature", long_name="air virtual temperature", units="K"): ...
class PressureOnCellK(Quantity, dims=CELL_K, standard_name="air_pressure", long_name="air pressure", units="Pa"): ...
class PressureOnCellKHalf(Quantity, dims=CELL_KHALF, standard_name="air_pressure", long_name="air pressure at half levels", units="Pa"): ...
class SurfacePressureOnCell(Quantity, dims=CELL, standard_name="air_pressure_at_ground_level", long_name="air pressure at ground level", units="Pa"): ...

# --- dycore diagnostics (DiagnosticStateNonHydro) ---

class ContravariantCorrectionOnCellKHalf(Quantity, dims=CELL_KHALF, long_name="contravariant correction at cell centers on half levels (w_concorr_c)", units="m s-1", precision="vp"): ...
class PerturbedExnerOnCellK(Quantity, dims=CELL_K, long_name="perturbation of the exner function (exner_pr)", units="1"): ...
class ExnerTendencyDueToSlowPhysicsOnCellK(Tendency, dims=CELL_K, long_name="tendency of the exner function due to slow physics (ddt_exner_phy)", units="s-1", precision="vp"): ...
class GrfTendencyOfRhoOnCellK(Tendency, dims=CELL_K, long_name="tendency of density from grid refinement (grf_tend_rho)", units="kg m-3 s-1"): ...
class GrfTendencyOfThetaVOnCellK(Tendency, dims=CELL_K, long_name="tendency of virtual potential temperature from grid refinement (grf_tend_thv)", units="K s-1"): ...
class GrfTendencyOfWOnCellKHalf(Tendency, dims=CELL_KHALF, long_name="tendency of vertical wind from grid refinement (grf_tend_w)", units="m s-2"): ...
class GrfTendencyOfVnOnEdgeK(Tendency, dims=EDGE_K, long_name="tendency of normal wind from grid refinement (grf_tend_vn)", units="m s-2"): ...
class MassFluxOnEdgeK(Quantity, dims=EDGE_K, long_name="mass flux at edges on model levels (mass_fl_e)", units="kg m-2 s-1"): ...
class NormalWindTendencyDueToSlowPhysicsOnEdgeK(Tendency, dims=EDGE_K, long_name="tendency of normal wind due to slow physics (ddt_vn_phy)", units="m s-2", precision="vp"): ...
class NormalWindAdvectiveTendencyOnEdgeK(Tendency, dims=EDGE_K, long_name="advective tendency of normal wind, including the Coriolis force (ddt_vn_apc)", units="m s-2", precision="vp"): ...
class VerticalWindAdvectiveTendencyOnCellKHalf(Tendency, dims=CELL_KHALF, long_name="advective tendency of vertical wind (ddt_w_adv)", units="m s-2", precision="vp"): ...
class RhoIauIncrementOnCellK(Quantity, dims=CELL_K, long_name="moist density increment of the incremental analysis update (rho_incr)", units="kg m-3", precision="vp"): ...
class NormalWindIauIncrementOnEdgeK(Quantity, dims=EDGE_K, long_name="normal wind increment of the incremental analysis update (vn_incr)", units="m s-1", precision="vp"): ...
class ExnerIauIncrementOnCellK(Quantity, dims=CELL_K, long_name="exner function increment of the incremental analysis update (exner_incr)", units="1", precision="vp"): ...
class ExnerDynamicalIncrementOnCellK(Quantity, dims=CELL_K, long_name="exner function increment by the dynamics (exner_dyn_incr)", units="1", precision="vp"): ...

# --- fluxes prepared for the tracer advection ---

class MassFluxOnCellKHalf(Quantity, dims=CELL_KHALF, long_name="vertical mass flux at cell centers on half levels (mass_flx_ic)", units="kg m-2 s-1"): ...
class VolumetricFluxOnCellKHalf(Quantity, dims=CELL_KHALF, long_name="vertical volumetric flux at cell centers on half levels (vol_flx_ic)", units="m s-1"): ...

# --- diffusion diagnostics ---

class HorizontalWindDeformationOnCellKHalf(Quantity, dims=CELL_KHALF, long_name="horizontal wind field deformation (hdef_ic)", units="s-2", precision="vp"): ...
class DivergenceOnCellKHalf(Quantity, dims=CELL_KHALF, long_name="horizontal wind divergence (div_ic)", units="s-1", precision="vp"): ...
class ZonalGradientOfWOnCellKHalf(Quantity, dims=CELL_KHALF, long_name="zonal gradient of vertical wind speed (dwdx)", units="s-1", precision="vp"): ...
class MeridionalGradientOfWOnCellKHalf(Quantity, dims=CELL_KHALF, long_name="meridional gradient of vertical wind speed (dwdy)", units="s-1", precision="vp"): ...

# --- tracer advection diagnostics ---

class AirMassOnCellK(Quantity, dims=CELL_K, long_name="mass of air in the layer per unit area", units="kg m-2"): ...
class GrfTendencyOfTracerOnCellK(Tendency, dims=CELL_K, long_name="tracer tendency from grid refinement (grf_tend_tracer)", units="s-1"): ...
class HorizontalTracerFluxOnEdgeK(Quantity, dims=EDGE_K, long_name="horizontal tracer flux at edges (hfl_tracer)", units="kg m-1 s-1"): ...
class VerticalTracerFluxOnCellKHalf(Quantity, dims=CELL_KHALF, long_name="vertical tracer flux at cell centers (vfl_tracer)", units="kg m-1 s-1"): ...

# --- physics tendencies ---

class TendencyOfTemperatureOnCellK(Tendency, dims=CELL_K, standard_name="tendency_of_air_temperature", long_name="tendency of air temperature", units="K s-1"): ...
class TendencyOfQvOnCellK(Tendency, dims=CELL_K, standard_name="tendency_of_specific_humidity", long_name="tendency of ratio of water vapor mass to total moist air parcel mass", units="s-1"): ...
class TendencyOfQcOnCellK(Tendency, dims=CELL_K, standard_name="tendency_of_specific_cloud_content", long_name="tendency of ratio of cloud water mass to total moist air parcel mass", units="s-1"): ...
class TendencyOfQiOnCellK(Tendency, dims=CELL_K, standard_name="tendency_of_specific_ice_content", long_name="tendency of ratio of cloud ice mass to total moist air parcel mass", units="s-1"): ...
class TendencyOfQrOnCellK(Tendency, dims=CELL_K, standard_name="tendency_of_specific_rain_content", long_name="tendency of ratio of rain mass to total moist air parcel mass", units="s-1"): ...
class TendencyOfQsOnCellK(Tendency, dims=CELL_K, standard_name="tendency_of_specific_snow_content", long_name="tendency of ratio of snow mass to total moist air parcel mass", units="s-1"): ...
class TendencyOfQgOnCellK(Tendency, dims=CELL_K, standard_name="tendency_of_specific_graupel_content", long_name="tendency of ratio of graupel mass to total moist air parcel mass", units="s-1"): ...
class TendencyOfUOnCellK(Tendency, dims=CELL_K, standard_name="tendency_of_eastward_wind", long_name="tendency of eastward wind component", units="m s-2"): ...
class TendencyOfVOnCellK(Tendency, dims=CELL_K, standard_name="tendency_of_northward_wind", long_name="tendency of northward wind component", units="m s-2"): ...
class TendencyOfWOnCellKHalf(Tendency, dims=CELL_KHALF, standard_name="tendency_of_upward_air_velocity", long_name="tendency of vertical air velocity component", units="m s-2"): ...
class TendencyOfVnOnEdgeK(Tendency, dims=EDGE_K, long_name="tendency of velocity normal to edge", units="m s-2"): ...

# --- precipitation (muphys) ---

class PrecipitationFluxOnCellK(Quantity, dims=CELL_K, standard_name="precipitation_flux", long_name="total precipitation flux (rain + snow + graupel + ice)", units="kg m-2 s-1"): ...
class RainfallFluxOnCellK(Quantity, dims=CELL_K, standard_name="rainfall_flux", long_name="rainfall flux", units="kg m-2 s-1"): ...
class SnowfallFluxOnCellK(Quantity, dims=CELL_K, standard_name="snowfall_flux", long_name="snowfall flux", units="kg m-2 s-1"): ...
class GraupelfallFluxOnCellK(Quantity, dims=CELL_K, standard_name="graupelfall_flux", long_name="graupelfall flux", units="kg m-2 s-1"): ...
class IcefallFluxOnCellK(Quantity, dims=CELL_K, standard_name="icefall_flux", long_name="icefall flux", units="kg m-2 s-1"): ...
class PrecipitationEnergyFluxOnCellK(Quantity, dims=CELL_K, standard_name="precipitation_energy_flux", long_name="energy flux carried by precipitation", units="W m-2"): ...

# --- turbulent mixing (tmx) ---

class HeatCapacityOnCellK(Quantity, dims=CELL_K, long_name="isochoric heat capacity of the air per unit area (cvair)", units="J K-1 m-2"): ...
class EvapotranspirationOnCell(Quantity, dims=CELL, long_name="surface evapotranspiration flux (evspsbl)", units="kg m-2 s-1"): ...
class SensibleHeatFluxOnCell(Quantity, dims=CELL, long_name="surface sensible heat flux (hfss)", units="W m-2"): ...
class UStressOnCell(Quantity, dims=CELL, long_name="zonal surface wind stress (tauu)", units="N m-2"): ...
class VStressOnCell(Quantity, dims=CELL, long_name="meridional surface wind stress (tauv)", units="N m-2"): ...
class SnowCanopyMeltHeatOnCell(Quantity, dims=CELL, long_name="heat used to melt snow on the canopy (q_snocpymlt)", units="W m-2"): ...
class DryStaticEnergyOnCellK(Quantity, dims=CELL_K, long_name="dry static energy cp*T + g*z (cptgz)", units="J kg-1"): ...
class DivergenceOnCellK(Quantity, dims=CELL_K, long_name="horizontal wind divergence (div_c)", units="s-1"): ...
class TurbulentViscosityOnCellK(Quantity, dims=CELL_K, long_name="turbulent viscosity at cell centers (km_c)", units="kg m-1 s-1"): ...
class ExchangeCoefficientForMomentumOnCellK(Quantity, dims=CELL_K, long_name="turbulent exchange coefficient for momentum (km)", units="kg m-1 s-1"): ...
class ExchangeCoefficientForHeatOnCellK(Quantity, dims=CELL_K, long_name="turbulent exchange coefficient for heat (kh)", units="kg m-1 s-1"): ...
class KineticEnergyDissipationOnCellK(Quantity, dims=CELL_K, long_name="kinetic energy dissipated by the wind diffusion, per layer (dissip_ke)", units="W m-2"): ...
class TurbulentHeatingOnCellK(Quantity, dims=CELL_K, long_name="turbulent heating, per layer", units="W m-2"): ...
class VerticallyIntegratedDryStaticEnergyOnCell(Quantity, dims=CELL, long_name="vertical integral of the dry static energy (cptgz_vi)", units="J m-2"): ...
class VerticallyIntegratedKineticEnergyDissipationOnCell(Quantity, dims=CELL, long_name="vertical integral of the dissipated kinetic energy (dissip_ke_vi)", units="W m-2"): ...
class VerticallyIntegratedInternalEnergyOnCell(Quantity, dims=CELL, long_name="vertical integral of the internal energy (int_energy_vi)", units="J m-2"): ...
class TendencyOfVerticallyIntegratedInternalEnergyOnCell(Tendency, dims=CELL, long_name="tendency of the vertically integrated internal energy (tend_int_energy_vi)", units="W m-2"): ...

# fmt: on
