# ICON4Py - ICON inspired code in Python and GT4Py
#
# Copyright (c) 2022-2024, ETH Zurich and MeteoSwiss
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause

"""Code-GENERATION driver: `emit_module()` writes a builder's DSL source
text into a COMMITTED file under `core/generated/`, and
`check_regenerated()` is the drift-guard test helper that re-runs the
same builder and asserts the committed file hasn't drifted from it.

DESIGN CONSTRAINT (BINDING, M0 gate report amendment): every builder
passed to `emit_module` MUST emit SPLIT operators -- one
`@gtx.field_operator` per bin GROUP of at most 8 consecutive bins, never
one monolithic operator spanning an entire hydrometeor category's bins.
`spikes/spike_b_collection_codegen.py` (F5 SS6) measured a single
unrolled 40-bin collection-kernel operator's `gtfn_cpu` compile at
~2579s (~43 minutes) -- this is the concrete cost SPLIT operators avoid.
The first REAL (non-demonstration) builder against this module will be
M2's collection kernel, and it must chunk by destination bin (banded,
<=8 bins per operator) from the start; M1 ships only
`codegen.templates.build_axpy_per_bin`, a trivial builder whose own
output already demonstrates this chunking (one field_operator per
bin-group of <=8 bins once `nbins > 8`) to prove the
`emit_module`/`check_regenerated` pipeline end-to-end.
`codegen.templates.chunk_bins` is the shared chunking helper any builder
should reuse.

Generated files are COMMITTED to git under `core/generated/{name}.py`,
each carrying this exact license header plus a
"# GENERATED by codegen/generate.py -- do not edit" banner (and the
builder's dotted name + params, for auditability). `emit_module` is run
OFFLINE (by a developer, not by the test suite) to produce/update a
committed file; `check_regenerated` is the read-only counterpart a
pytest test calls to assert the committed file still matches what its
builder would currently produce -- it never writes to disk, so a
drifted generator fails loudly instead of silently "fixing" the
committed file out from under a reviewer.

Loading a generated module back uses the same idiom as
`spikes/common.py::load_generated_operator` (F5 SS6): gt4py's
`@gtx.field_operator` decorator parses the operator body via
`inspect.getsource`, which needs a real file on disk (satisfied here,
since `core/generated/{name}.py` genuinely is one); loading via
`importlib.util.spec_from_file_location` rather than a plain `import`
statement additionally guarantees a FRESH module object even if this
exact dotted name was already imported earlier in the same process
(e.g. by an earlier test), so repeated `check_regenerated`/
`load_generated_module` calls within one pytest session never see a
stale cached module.

Builders emit plain, readable-but-not-hand-wrapped source (e.g. a long
per-bin tuple return type on one line); rather than have every builder
hand-replicate `ruff format`'s exact line-wrapping algorithm, both
`emit_module` (before writing) and `check_regenerated` (on its in-memory
"fresh" text, never written to disk) pipe the builder's raw output
through the SAME `ruff check --fix` + `ruff format` normalization this
repo's own pre-commit hooks apply (`_finalize`, using a plain `ruff`
executable on `PATH`/the venv if available, else the pre-commit hooks'
own `uv run --group dev --frozen --isolated ruff ...` invocation as a
fallback) -- so the committed file is always pre-commit-clean by
construction, and `check_regenerated`'s comparison stays apples-to-apples
regardless of the builder's own formatting.
"""

from __future__ import annotations

import difflib
import importlib.util
import shutil
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path
from types import ModuleType


_LICENSE_HEADER = """\
# ICON4Py - ICON inspired code in Python and GT4Py
#
# Copyright (c) 2022-2024, ETH Zurich and MeteoSwiss
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause
"""

_GENERATED_PACKAGE = "icon4py.model.atmosphere.subgrid_scale_physics.amps.core.generated"

GENERATED_DIR = Path(__file__).resolve().parent.parent / "core" / "generated"


def _banner(build: Callable[..., str], params: dict[str, object]) -> str:
    # NOTE: deliberately NOT written as "name(params)" or "key: value" /
    # "key=value" alone on a comment line -- ruff's eradicate rule
    # (ERA001, "commented-out code") flags any comment whose text happens
    # to parse as valid Python (a call, an annotation, an assignment),
    # which would leave a hard `ruff check` failure baked into every
    # committed generated file. Prose with a trailing period ("Builder
    # X -- params: ...  .") does not parse as an expression/statement and
    # is not flagged (verified empirically against this ruff version).
    build_name = f"{build.__module__}.{build.__qualname__}"
    params_repr = ", ".join(f"{key}={value!r}" for key, value in params.items())
    tail = f"params: {params_repr}." if params_repr else "no params."
    return f"# GENERATED by codegen/generate.py -- do not edit.\n# Builder {build_name} -- {tail}\n"


def _ruff_command(*args: str) -> list[str]:
    """A direct `ruff` invocation if the executable is on `PATH` (fast --
    the common case, since `ruff` is always installed alongside the dev
    tooling this repo's tests already run under); otherwise fall back to
    the exact `uv run` invocation the `ruff-check`/`ruff-format`
    pre-commit hooks use, so results match pre-commit either way."""
    ruff = shutil.which("ruff")
    if ruff is not None:
        return [ruff, *args]
    return ["uv", "run", "--group", "dev", "--frozen", "--isolated", "ruff", *args]


def _finalize(source: str, *, filename: str) -> str:
    """Normalize generated source with `ruff check --fix` then
    `ruff format`, the same two steps (same order) this repo's
    `ruff-check`/`ruff-format` pre-commit hooks apply -- see module
    docstring."""
    stdin_arg = f"--stdin-filename={filename}"
    checked = subprocess.run(
        _ruff_command("check", "--fix", "--exit-zero", stdin_arg, "-"),
        input=source,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    formatted = subprocess.run(
        _ruff_command("format", stdin_arg, "-"),
        input=checked,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    return formatted


def _render_module(name: str, build: Callable[..., str], params: dict[str, object]) -> str:
    body = build(**params)
    raw = _LICENSE_HEADER + "\n" + _banner(build, params) + "\n" + body
    return _finalize(raw, filename=f"{name}.py")


def load_generated_module(name: str) -> ModuleType:
    """Load `core/generated/{name}.py` as a fresh module object (spike
    `load_generated_operator` pattern, F5 SS6 -- see module docstring for
    why `importlib.util` is used instead of a plain `import`)."""
    path = GENERATED_DIR / f"{name}.py"
    qualname = f"{_GENERATED_PACKAGE}.{name}"
    spec = importlib.util.spec_from_file_location(qualname, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load generated module from {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[qualname] = module
    spec.loader.exec_module(module)
    return module


def emit_module(name: str, build: Callable[..., str], **params: object) -> Path:
    """Write `build(**params)`'s DSL source (license header + GENERATED
    banner prepended) to the COMMITTED `core/generated/{name}.py`, then
    load it (validating the emitted source is at least importable)
    before returning its path. Run this offline, by a developer, when a
    builder is new or has changed -- NOT from the test suite (see module
    docstring; tests should call `check_regenerated` instead, which
    never writes).
    """
    source = _render_module(name, build, params)
    path = GENERATED_DIR / f"{name}.py"
    path.write_text(source)
    load_generated_module(name)
    return path


def check_regenerated(name: str, build: Callable[..., str], **params: object) -> None:
    """Drift guard: assert `core/generated/{name}.py` (already committed
    to disk) is byte-identical to what `build(**params)` currently
    produces. Raises `AssertionError` with a unified diff on mismatch.
    Read-only -- never calls `emit_module`/writes to disk (see module
    docstring).
    """
    path = GENERATED_DIR / f"{name}.py"
    if not path.exists():
        raise AssertionError(f"{path} does not exist -- run emit_module() to create it first")
    committed = path.read_text()
    fresh = _render_module(name, build, params)
    if committed != fresh:
        diff = "\n".join(
            difflib.unified_diff(
                committed.splitlines(),
                fresh.splitlines(),
                fromfile=f"committed:{path.name}",
                tofile=f"regenerated:{path.name}",
                lineterm="",
            )
        )
        build_name = f"{build.__module__}.{build.__qualname__}"
        raise AssertionError(
            f"core/generated/{name}.py has drifted from its builder ({build_name}) -- "
            f"re-run emit_module(...) to update it. Diff:\n{diff}"
        )
