#define _CFFI_USE_EMBEDDING
#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

#define _CFFI_MODULE_NAME  "identity_plugin"
static const char _CFFI_PYTHON_STARTUP_CODE[] = {
// # NB. this is not a string because of a size limit in MSVC
// '# necessary imports for generated code to work\n
35,32,110,101,99,101,115,115,97,114,121,32,105,109,112,111,114,116,115,32,102,
111,114,32,103,101,110,101,114,97,116,101,100,32,99,111,100,101,32,116,111,32,
119,111,114,107,10,
// 'from identity_plugin import ffi\n
102,114,111,109,32,105,100,101,110,116,105,116,121,95,112,108,117,103,105,110,
32,105,109,112,111,114,116,32,102,102,105,10,
// 'import numpy as np\n
105,109,112,111,114,116,32,110,117,109,112,121,32,97,115,32,110,112,10,
// 'import cupy as cp\n
105,109,112,111,114,116,32,99,117,112,121,32,97,115,32,99,112,10,
// 'from numpy.typing import NDArray\n
102,114,111,109,32,110,117,109,112,121,46,116,121,112,105,110,103,32,105,109,
112,111,114,116,32,78,68,65,114,114,97,121,10,
// 'from gt4py.next.ffront.fbuiltins import int32\n
102,114,111,109,32,103,116,52,112,121,46,110,101,120,116,46,102,102,114,111,
110,116,46,102,98,117,105,108,116,105,110,115,32,105,109,112,111,114,116,32,
105,110,116,51,50,10,
// 'from gt4py.next.iterator.embedded import np_as_located_field\n
102,114,111,109,32,103,116,52,112,121,46,110,101,120,116,46,105,116,101,114,
97,116,111,114,46,101,109,98,101,100,100,101,100,32,105,109,112,111,114,116,
32,110,112,95,97,115,95,108,111,99,97,116,101,100,95,102,105,101,108,100,10,
// 'from gt4py.next import as_field\n
102,114,111,109,32,103,116,52,112,121,46,110,101,120,116,32,105,109,112,111,
114,116,32,97,115,95,102,105,101,108,100,10,
// 'from gt4py.next.program_processors.runners.gtfn import run_gtfn, run_gtfn_gpu\n
102,114,111,109,32,103,116,52,112,121,46,110,101,120,116,46,112,114,111,103,
114,97,109,95,112,114,111,99,101,115,115,111,114,115,46,114,117,110,110,101,
114,115,46,103,116,102,110,32,105,109,112,111,114,116,32,114,117,110,95,103,
116,102,110,44,32,114,117,110,95,103,116,102,110,95,103,112,117,10,
// 'from gt4py.next.program_processors.runners.roundtrip import backend as run_roundtrip\n
102,114,111,109,32,103,116,52,112,121,46,110,101,120,116,46,112,114,111,103,
114,97,109,95,112,114,111,99,101,115,115,111,114,115,46,114,117,110,110,101,
114,115,46,114,111,117,110,100,116,114,105,112,32,105,109,112,111,114,116,32,
98,97,99,107,101,110,100,32,97,115,32,114,117,110,95,114,111,117,110,100,116,
114,105,112,10,
// 'from icon4py.model.common.grid.simple import SimpleGrid\n
102,114,111,109,32,105,99,111,110,52,112,121,46,109,111,100,101,108,46,99,111,
109,109,111,110,46,103,114,105,100,46,115,105,109,112,108,101,32,105,109,112,
111,114,116,32,83,105,109,112,108,101,71,114,105,100,10,
// '\n
10,
// '# all other imports from the module from which the function is being wrapped\n
35,32,97,108,108,32,111,116,104,101,114,32,105,109,112,111,114,116,115,32,102,
114,111,109,32,116,104,101,32,109,111,100,117,108,101,32,102,114,111,109,32,
119,104,105,99,104,32,116,104,101,32,102,117,110,99,116,105,111,110,32,105,115,
32,98,101,105,110,103,32,119,114,97,112,112,101,100,10,
// 'from gt4py.next.common import GridType\n
102,114,111,109,32,103,116,52,112,121,46,110,101,120,116,46,99,111,109,109,111,
110,32,105,109,112,111,114,116,32,71,114,105,100,84,121,112,101,10,
// 'from gt4py.next.ffront.decorator import field_operator\n
102,114,111,109,32,103,116,52,112,121,46,110,101,120,116,46,102,102,114,111,
110,116,46,100,101,99,111,114,97,116,111,114,32,105,109,112,111,114,116,32,102,
105,101,108,100,95,111,112,101,114,97,116,111,114,10,
// 'from gt4py.next.ffront.decorator import program\n
102,114,111,109,32,103,116,52,112,121,46,110,101,120,116,46,102,102,114,111,
110,116,46,100,101,99,111,114,97,116,111,114,32,105,109,112,111,114,116,32,112,
114,111,103,114,97,109,10,
// 'from gt4py.next.ffront.fbuiltins import Field\n
102,114,111,109,32,103,116,52,112,121,46,110,101,120,116,46,102,102,114,111,
110,116,46,102,98,117,105,108,116,105,110,115,32,105,109,112,111,114,116,32,
70,105,101,108,100,10,
// 'from gt4py.next.ffront.fbuiltins import float64\n
102,114,111,109,32,103,116,52,112,121,46,110,101,120,116,46,102,102,114,111,
110,116,46,102,98,117,105,108,116,105,110,115,32,105,109,112,111,114,116,32,
102,108,111,97,116,54,52,10,
// 'from gt4py.next.ffront.fbuiltins import int32\n
102,114,111,109,32,103,116,52,112,121,46,110,101,120,116,46,102,102,114,111,
110,116,46,102,98,117,105,108,116,105,110,115,32,105,109,112,111,114,116,32,
105,110,116,51,50,10,
// 'from icon4py.model.common.dimension import CellDim\n
102,114,111,109,32,105,99,111,110,52,112,121,46,109,111,100,101,108,46,99,111,
109,109,111,110,46,100,105,109,101,110,115,105,111,110,32,105,109,112,111,114,
116,32,67,101,108,108,68,105,109,10,
// 'from icon4py.model.common.dimension import EdgeDim\n
102,114,111,109,32,105,99,111,110,52,112,121,46,109,111,100,101,108,46,99,111,
109,109,111,110,46,100,105,109,101,110,115,105,111,110,32,105,109,112,111,114,
116,32,69,100,103,101,68,105,109,10,
// 'from icon4py.model.common.dimension import KDim\n
102,114,111,109,32,105,99,111,110,52,112,121,46,109,111,100,101,108,46,99,111,
109,109,111,110,46,100,105,109,101,110,115,105,111,110,32,105,109,112,111,114,
116,32,75,68,105,109,10,
// 'from icon4py.model.common.type_alias import wpfloat\n
102,114,111,109,32,105,99,111,110,52,112,121,46,109,111,100,101,108,46,99,111,
109,109,111,110,46,116,121,112,101,95,97,108,105,97,115,32,105,109,112,111,114,
116,32,119,112,102,108,111,97,116,10,
// 'from gt4py.next.program_processors.runners.gtfn import run_gtfn_gpu\n
102,114,111,109,32,103,116,52,112,121,46,110,101,120,116,46,112,114,111,103,
114,97,109,95,112,114,111,99,101,115,115,111,114,115,46,114,117,110,110,101,
114,115,46,103,116,102,110,32,105,109,112,111,114,116,32,114,117,110,95,103,
116,102,110,95,103,112,117,10,
// '\n
10,
// '\n
10,
// 'import logging\n
105,109,112,111,114,116,32,108,111,103,103,105,110,103,10,
// '\n
10,
// 'log_format = "%(asctime)s.%(msecs)03d - %(levelname)s - %(message)s"\n
108,111,103,95,102,111,114,109,97,116,32,61,32,34,37,40,97,115,99,116,105,109,
101,41,115,46,37,40,109,115,101,99,115,41,48,51,100,32,45,32,37,40,108,101,118,
101,108,110,97,109,101,41,115,32,45,32,37,40,109,101,115,115,97,103,101,41,115,
34,10,
// '\n
10,
// 'logging.basicConfig(\n
108,111,103,103,105,110,103,46,98,97,115,105,99,67,111,110,102,105,103,40,10,
// '    filename="py_cffi.log", level=logging.DEBUG, format=log_format, datefmt="%Y-%m-%d %H:%M:%S"\n
32,32,32,32,102,105,108,101,110,97,109,101,61,34,112,121,95,99,102,102,105,46,
108,111,103,34,44,32,108,101,118,101,108,61,108,111,103,103,105,110,103,46,68,
69,66,85,71,44,32,102,111,114,109,97,116,61,108,111,103,95,102,111,114,109,97,
116,44,32,100,97,116,101,102,109,116,61,34,37,89,45,37,109,45,37,100,32,37,72,
58,37,77,58,37,83,34,10,
// ')\n
41,10,
// '\n
10,
// '# We need a grid to pass offset providers\n
35,32,87,101,32,110,101,101,100,32,97,32,103,114,105,100,32,116,111,32,112,97,
115,115,32,111,102,102,115,101,116,32,112,114,111,118,105,100,101,114,115,10,
// 'grid = SimpleGrid()\n
103,114,105,100,32,61,32,83,105,109,112,108,101,71,114,105,100,40,41,10,
// '\n
10,
// '\n
10,
// 'from icon4pytools.py2fgen.wrappers.simple import identity\n
102,114,111,109,32,105,99,111,110,52,112,121,116,111,111,108,115,46,112,121,
50,102,103,101,110,46,119,114,97,112,112,101,114,115,46,115,105,109,112,108,
101,32,105,109,112,111,114,116,32,105,100,101,110,116,105,116,121,10,
// '\n
10,
// '\n
10,
// 'def unpack(ptr, *sizes: int) -> NDArray:\n
100,101,102,32,117,110,112,97,99,107,40,112,116,114,44,32,42,115,105,122,101,
115,58,32,105,110,116,41,32,45,62,32,78,68,65,114,114,97,121,58,10,
// '    """\n
32,32,32,32,34,34,34,10,
// '    Converts a C pointer pointing to data in Fortran (column-major) order into a NumPy array.\n
32,32,32,32,67,111,110,118,101,114,116,115,32,97,32,67,32,112,111,105,110,116,
101,114,32,112,111,105,110,116,105,110,103,32,116,111,32,100,97,116,97,32,105,
110,32,70,111,114,116,114,97,110,32,40,99,111,108,117,109,110,45,109,97,106,
111,114,41,32,111,114,100,101,114,32,105,110,116,111,32,97,32,78,117,109,80,
121,32,97,114,114,97,121,46,10,
// '\n
10,
// '    This function facilitates the handling of numerical data shared between C (or Fortran) and Python,\n
32,32,32,32,84,104,105,115,32,102,117,110,99,116,105,111,110,32,102,97,99,105,
108,105,116,97,116,101,115,32,116,104,101,32,104,97,110,100,108,105,110,103,
32,111,102,32,110,117,109,101,114,105,99,97,108,32,100,97,116,97,32,115,104,
97,114,101,100,32,98,101,116,119,101,101,110,32,67,32,40,111,114,32,70,111,114,
116,114,97,110,41,32,97,110,100,32,80,121,116,104,111,110,44,10,
// '    especially when the data originates from Fortran routines that use column-major storage order.\n
32,32,32,32,101,115,112,101,99,105,97,108,108,121,32,119,104,101,110,32,116,
104,101,32,100,97,116,97,32,111,114,105,103,105,110,97,116,101,115,32,102,114,
111,109,32,70,111,114,116,114,97,110,32,114,111,117,116,105,110,101,115,32,116,
104,97,116,32,117,115,101,32,99,111,108,117,109,110,45,109,97,106,111,114,32,
115,116,111,114,97,103,101,32,111,114,100,101,114,46,10,
// '    It creates a NumPy array that directly views the data pointed to by `ptr`, without copying, and reshapes\n
32,32,32,32,73,116,32,99,114,101,97,116,101,115,32,97,32,78,117,109,80,121,32,
97,114,114,97,121,32,116,104,97,116,32,100,105,114,101,99,116,108,121,32,118,
105,101,119,115,32,116,104,101,32,100,97,116,97,32,112,111,105,110,116,101,100,
32,116,111,32,98,121,32,96,112,116,114,96,44,32,119,105,116,104,111,117,116,
32,99,111,112,121,105,110,103,44,32,97,110,100,32,114,101,115,104,97,112,101,
115,10,
// "    it according to the specified dimensions. The resulting NumPy array uses Fortran order ('F') to preserve\n
32,32,32,32,105,116,32,97,99,99,111,114,100,105,110,103,32,116,111,32,116,104,
101,32,115,112,101,99,105,102,105,101,100,32,100,105,109,101,110,115,105,111,
110,115,46,32,84,104,101,32,114,101,115,117,108,116,105,110,103,32,78,117,109,
80,121,32,97,114,114,97,121,32,117,115,101,115,32,70,111,114,116,114,97,110,
32,111,114,100,101,114,32,40,39,70,39,41,32,116,111,32,112,114,101,115,101,114,
118,101,10,
// '    the original data layout.\n
32,32,32,32,116,104,101,32,111,114,105,103,105,110,97,108,32,100,97,116,97,32,
108,97,121,111,117,116,46,10,
// '\n
10,
// '    Args:\n
32,32,32,32,65,114,103,115,58,10,
// '        ptr (CData): A CFFI pointer to the beginning of the data array. This pointer should reference\n
32,32,32,32,32,32,32,32,112,116,114,32,40,67,68,97,116,97,41,58,32,65,32,67,
70,70,73,32,112,111,105,110,116,101,114,32,116,111,32,116,104,101,32,98,101,
103,105,110,110,105,110,103,32,111,102,32,116,104,101,32,100,97,116,97,32,97,
114,114,97,121,46,32,84,104,105,115,32,112,111,105,110,116,101,114,32,115,104,
111,117,108,100,32,114,101,102,101,114,101,110,99,101,10,
// '            a contiguous block of memory whose total size matches the product of the specified dimensions.\n
32,32,32,32,32,32,32,32,32,32,32,32,97,32,99,111,110,116,105,103,117,111,117,
115,32,98,108,111,99,107,32,111,102,32,109,101,109,111,114,121,32,119,104,111,
115,101,32,116,111,116,97,108,32,115,105,122,101,32,109,97,116,99,104,101,115,
32,116,104,101,32,112,114,111,100,117,99,116,32,111,102,32,116,104,101,32,115,
112,101,99,105,102,105,101,100,32,100,105,109,101,110,115,105,111,110,115,46,
10,
// '        *sizes (int): Variable length argument list representing the dimensions of the array. The product\n
32,32,32,32,32,32,32,32,42,115,105,122,101,115,32,40,105,110,116,41,58,32,86,
97,114,105,97,98,108,101,32,108,101,110,103,116,104,32,97,114,103,117,109,101,
110,116,32,108,105,115,116,32,114,101,112,114,101,115,101,110,116,105,110,103,
32,116,104,101,32,100,105,109,101,110,115,105,111,110,115,32,111,102,32,116,
104,101,32,97,114,114,97,121,46,32,84,104,101,32,112,114,111,100,117,99,116,
10,
// '            of these sizes should match the total number of elements in the data block pointed to by `ptr`.\n
32,32,32,32,32,32,32,32,32,32,32,32,111,102,32,116,104,101,115,101,32,115,105,
122,101,115,32,115,104,111,117,108,100,32,109,97,116,99,104,32,116,104,101,32,
116,111,116,97,108,32,110,117,109,98,101,114,32,111,102,32,101,108,101,109,101,
110,116,115,32,105,110,32,116,104,101,32,100,97,116,97,32,98,108,111,99,107,
32,112,111,105,110,116,101,100,32,116,111,32,98,121,32,96,112,116,114,96,46,
10,
// '\n
10,
// '    Returns:\n
32,32,32,32,82,101,116,117,114,110,115,58,10,
// '        np.ndarray: A NumPy array view of the data pointed to by `ptr`. The array will have the shape\n
32,32,32,32,32,32,32,32,110,112,46,110,100,97,114,114,97,121,58,32,65,32,78,
117,109,80,121,32,97,114,114,97,121,32,118,105,101,119,32,111,102,32,116,104,
101,32,100,97,116,97,32,112,111,105,110,116,101,100,32,116,111,32,98,121,32,
96,112,116,114,96,46,32,84,104,101,32,97,114,114,97,121,32,119,105,108,108,32,
104,97,118,101,32,116,104,101,32,115,104,97,112,101,10,
// '        specified by `sizes` and the data type (`dtype`) corresponding to the C data type of `ptr`.\n
32,32,32,32,32,32,32,32,115,112,101,99,105,102,105,101,100,32,98,121,32,96,115,
105,122,101,115,96,32,97,110,100,32,116,104,101,32,100,97,116,97,32,116,121,
112,101,32,40,96,100,116,121,112,101,96,41,32,99,111,114,114,101,115,112,111,
110,100,105,110,103,32,116,111,32,116,104,101,32,67,32,100,97,116,97,32,116,
121,112,101,32,111,102,32,96,112,116,114,96,46,10,
// '        The array is created with Fortran order to match the original column-major data layout.\n
32,32,32,32,32,32,32,32,84,104,101,32,97,114,114,97,121,32,105,115,32,99,114,
101,97,116,101,100,32,119,105,116,104,32,70,111,114,116,114,97,110,32,111,114,
100,101,114,32,116,111,32,109,97,116,99,104,32,116,104,101,32,111,114,105,103,
105,110,97,108,32,99,111,108,117,109,110,45,109,97,106,111,114,32,100,97,116,
97,32,108,97,121,111,117,116,46,10,
// '\n
10,
// '    Note:\n
32,32,32,32,78,111,116,101,58,10,
// '        The function does not perform any copying of the data. Modifications to the resulting NumPy array\n
32,32,32,32,32,32,32,32,84,104,101,32,102,117,110,99,116,105,111,110,32,100,
111,101,115,32,110,111,116,32,112,101,114,102,111,114,109,32,97,110,121,32,99,
111,112,121,105,110,103,32,111,102,32,116,104,101,32,100,97,116,97,46,32,77,
111,100,105,102,105,99,97,116,105,111,110,115,32,116,111,32,116,104,101,32,114,
101,115,117,108,116,105,110,103,32,78,117,109,80,121,32,97,114,114,97,121,10,
// '        will affect the original data pointed to by `ptr`. Ensure that the lifetime of the data pointed to\n
32,32,32,32,32,32,32,32,119,105,108,108,32,97,102,102,101,99,116,32,116,104,
101,32,111,114,105,103,105,110,97,108,32,100,97,116,97,32,112,111,105,110,116,
101,100,32,116,111,32,98,121,32,96,112,116,114,96,46,32,69,110,115,117,114,101,
32,116,104,97,116,32,116,104,101,32,108,105,102,101,116,105,109,101,32,111,102,
32,116,104,101,32,100,97,116,97,32,112,111,105,110,116,101,100,32,116,111,10,
// '        by `ptr` extends beyond the use of the returned NumPy array to prevent data corruption or access\n
32,32,32,32,32,32,32,32,98,121,32,96,112,116,114,96,32,101,120,116,101,110,100,
115,32,98,101,121,111,110,100,32,116,104,101,32,117,115,101,32,111,102,32,116,
104,101,32,114,101,116,117,114,110,101,100,32,78,117,109,80,121,32,97,114,114,
97,121,32,116,111,32,112,114,101,118,101,110,116,32,100,97,116,97,32,99,111,
114,114,117,112,116,105,111,110,32,111,114,32,97,99,99,101,115,115,10,
// '        violations.\n
32,32,32,32,32,32,32,32,118,105,111,108,97,116,105,111,110,115,46,10,
// '    """\n
32,32,32,32,34,34,34,10,
// '    length = np.prod(sizes)\n
32,32,32,32,108,101,110,103,116,104,32,61,32,110,112,46,112,114,111,100,40,115,
105,122,101,115,41,10,
// '    c_type = ffi.getctype(ffi.typeof(ptr).item)\n
32,32,32,32,99,95,116,121,112,101,32,61,32,102,102,105,46,103,101,116,99,116,
121,112,101,40,102,102,105,46,116,121,112,101,111,102,40,112,116,114,41,46,105,
116,101,109,41,10,
// '\n
10,
// '    # Map C data types to NumPy dtypes\n
32,32,32,32,35,32,77,97,112,32,67,32,100,97,116,97,32,116,121,112,101,115,32,
116,111,32,78,117,109,80,121,32,100,116,121,112,101,115,10,
// '    dtype_map: dict[str, np.dtype] = {\n
32,32,32,32,100,116,121,112,101,95,109,97,112,58,32,100,105,99,116,91,115,116,
114,44,32,110,112,46,100,116,121,112,101,93,32,61,32,123,10,
// '        "int": np.dtype(np.int32),\n
32,32,32,32,32,32,32,32,34,105,110,116,34,58,32,110,112,46,100,116,121,112,101,
40,110,112,46,105,110,116,51,50,41,44,10,
// '        "double": np.dtype(np.float64),\n
32,32,32,32,32,32,32,32,34,100,111,117,98,108,101,34,58,32,110,112,46,100,116,
121,112,101,40,110,112,46,102,108,111,97,116,54,52,41,44,10,
// '    }\n
32,32,32,32,125,10,
// '    dtype = dtype_map.get(c_type, np.dtype(c_type))\n
32,32,32,32,100,116,121,112,101,32,61,32,100,116,121,112,101,95,109,97,112,46,
103,101,116,40,99,95,116,121,112,101,44,32,110,112,46,100,116,121,112,101,40,
99,95,116,121,112,101,41,41,10,
// '\n
10,
// '    # Create a NumPy array from the buffer, specifying the Fortran order\n
32,32,32,32,35,32,67,114,101,97,116,101,32,97,32,78,117,109,80,121,32,97,114,
114,97,121,32,102,114,111,109,32,116,104,101,32,98,117,102,102,101,114,44,32,
115,112,101,99,105,102,121,105,110,103,32,116,104,101,32,70,111,114,116,114,
97,110,32,111,114,100,101,114,10,
// '    arr = np.frombuffer(ffi.buffer(ptr, length * ffi.sizeof(c_type)), dtype=dtype).reshape(  # type: ignore\n
32,32,32,32,97,114,114,32,61,32,110,112,46,102,114,111,109,98,117,102,102,101,
114,40,102,102,105,46,98,117,102,102,101,114,40,112,116,114,44,32,108,101,110,
103,116,104,32,42,32,102,102,105,46,115,105,122,101,111,102,40,99,95,116,121,
112,101,41,41,44,32,100,116,121,112,101,61,100,116,121,112,101,41,46,114,101,
115,104,97,112,101,40,32,32,35,32,116,121,112,101,58,32,105,103,110,111,114,
101,10,
// '        sizes, order="F"\n
32,32,32,32,32,32,32,32,115,105,122,101,115,44,32,111,114,100,101,114,61,34,
70,34,10,
// '    )\n
32,32,32,32,41,10,
// '    return arr\n
32,32,32,32,114,101,116,117,114,110,32,97,114,114,10,
// '\n
10,
// '\n
10,
// 'def unpack_gpu(ptr, *sizes: int) -> cp.ndarray:\n
100,101,102,32,117,110,112,97,99,107,95,103,112,117,40,112,116,114,44,32,42,
115,105,122,101,115,58,32,105,110,116,41,32,45,62,32,99,112,46,110,100,97,114,
114,97,121,58,10,
// '    if not sizes:\n
32,32,32,32,105,102,32,110,111,116,32,115,105,122,101,115,58,10,
// '        raise ValueError("Sizes must be provided to determine the array shape.")\n
32,32,32,32,32,32,32,32,114,97,105,115,101,32,86,97,108,117,101,69,114,114,111,
114,40,34,83,105,122,101,115,32,109,117,115,116,32,98,101,32,112,114,111,118,
105,100,101,100,32,116,111,32,100,101,116,101,114,109,105,110,101,32,116,104,
101,32,97,114,114,97,121,32,115,104,97,112,101,46,34,41,10,
// '\n
10,
// '    length = np.prod(sizes)\n
32,32,32,32,108,101,110,103,116,104,32,61,32,110,112,46,112,114,111,100,40,115,
105,122,101,115,41,10,
// '    # c_type = ffi.getctype(ffi.typeof(ptr).item)\n
32,32,32,32,35,32,99,95,116,121,112,101,32,61,32,102,102,105,46,103,101,116,
99,116,121,112,101,40,102,102,105,46,116,121,112,101,111,102,40,112,116,114,
41,46,105,116,101,109,41,10,
// '\n
10,
// '    dtype_map = {\n
32,32,32,32,100,116,121,112,101,95,109,97,112,32,61,32,123,10,
// '        "int": cp.int32,\n
32,32,32,32,32,32,32,32,34,105,110,116,34,58,32,99,112,46,105,110,116,51,50,
44,10,
// '        "double": cp.float64,\n
32,32,32,32,32,32,32,32,34,100,111,117,98,108,101,34,58,32,99,112,46,102,108,
111,97,116,54,52,44,10,
// '    }\n
32,32,32,32,125,10,
// '    # dtype = dtype_map.get(c_type, None)\n
32,32,32,32,35,32,100,116,121,112,101,32,61,32,100,116,121,112,101,95,109,97,
112,46,103,101,116,40,99,95,116,121,112,101,44,32,78,111,110,101,41,10,
// '    dtype = cp.float64\n
32,32,32,32,100,116,121,112,101,32,61,32,99,112,46,102,108,111,97,116,54,52,
10,
// '    # if dtype is None:\n
32,32,32,32,35,32,105,102,32,100,116,121,112,101,32,105,115,32,78,111,110,101,
58,10,
// '    #     raise ValueError(f"Unsupported C data type: {c_type}")\n
32,32,32,32,35,32,32,32,32,32,114,97,105,115,101,32,86,97,108,117,101,69,114,
114,111,114,40,102,34,85,110,115,117,112,112,111,114,116,101,100,32,67,32,100,
97,116,97,32,116,121,112,101,58,32,123,99,95,116,121,112,101,125,34,41,10,
// '\n
10,
// '    # itemsize = ffi.sizeof(c_type)\n
32,32,32,32,35,32,105,116,101,109,115,105,122,101,32,61,32,102,102,105,46,115,
105,122,101,111,102,40,99,95,116,121,112,101,41,10,
// '    itemsize = 8\n
32,32,32,32,105,116,101,109,115,105,122,101,32,61,32,56,10,
// '    total_size = length * itemsize\n
32,32,32,32,116,111,116,97,108,95,115,105,122,101,32,61,32,108,101,110,103,116,
104,32,42,32,105,116,101,109,115,105,122,101,10,
// '\n
10,
// '    device_id = 0\n
32,32,32,32,100,101,118,105,99,101,95,105,100,32,61,32,48,10,
// '    with cp.cuda.Device(device_id):\n
32,32,32,32,119,105,116,104,32,99,112,46,99,117,100,97,46,68,101,118,105,99,
101,40,100,101,118,105,99,101,95,105,100,41,58,10,
// '        print(ptr)\n
32,32,32,32,32,32,32,32,112,114,105,110,116,40,112,116,114,41,10,
// '        ptr_val = int(ffi.cast("uintptr_t", ptr))\n
32,32,32,32,32,32,32,32,112,116,114,95,118,97,108,32,61,32,105,110,116,40,102,
102,105,46,99,97,115,116,40,34,117,105,110,116,112,116,114,95,116,34,44,32,112,
116,114,41,41,10,
// '        print(ptr_val)\n
32,32,32,32,32,32,32,32,112,114,105,110,116,40,112,116,114,95,118,97,108,41,
10,
// '        mem = cp.cuda.UnownedMemory(ptr_val, total_size, owner=ptr, device_id=device_id)\n
32,32,32,32,32,32,32,32,109,101,109,32,61,32,99,112,46,99,117,100,97,46,85,110,
111,119,110,101,100,77,101,109,111,114,121,40,112,116,114,95,118,97,108,44,32,
116,111,116,97,108,95,115,105,122,101,44,32,111,119,110,101,114,61,112,116,114,
44,32,100,101,118,105,99,101,95,105,100,61,100,101,118,105,99,101,95,105,100,
41,10,
// '        print(mem)\n
32,32,32,32,32,32,32,32,112,114,105,110,116,40,109,101,109,41,10,
// '        memptr = cp.cuda.MemoryPointer(mem, 0)\n
32,32,32,32,32,32,32,32,109,101,109,112,116,114,32,61,32,99,112,46,99,117,100,
97,46,77,101,109,111,114,121,80,111,105,110,116,101,114,40,109,101,109,44,32,
48,41,10,
// '        print(memptr)\n
32,32,32,32,32,32,32,32,112,114,105,110,116,40,109,101,109,112,116,114,41,10,
// '\n
10,
// '        # invalid memory access?\n
32,32,32,32,32,32,32,32,35,32,105,110,118,97,108,105,100,32,109,101,109,111,
114,121,32,97,99,99,101,115,115,63,10,
// '        arr = cp.ndarray(shape=sizes, dtype=dtype, memptr=memptr, order="F")\n
32,32,32,32,32,32,32,32,97,114,114,32,61,32,99,112,46,110,100,97,114,114,97,
121,40,115,104,97,112,101,61,115,105,122,101,115,44,32,100,116,121,112,101,61,
100,116,121,112,101,44,32,109,101,109,112,116,114,61,109,101,109,112,116,114,
44,32,111,114,100,101,114,61,34,70,34,41,10,
// '        print(arr)\n
32,32,32,32,32,32,32,32,112,114,105,110,116,40,97,114,114,41,10,
// '        print(type(arr))\n
32,32,32,32,32,32,32,32,112,114,105,110,116,40,116,121,112,101,40,97,114,114,
41,41,10,
// '\n
10,
// '        # arr = np.frombuffer(ffi.buffer(ptr, total_size), dtype=dtype).reshape(  # type: ignore\n
32,32,32,32,32,32,32,32,35,32,97,114,114,32,61,32,110,112,46,102,114,111,109,
98,117,102,102,101,114,40,102,102,105,46,98,117,102,102,101,114,40,112,116,114,
44,32,116,111,116,97,108,95,115,105,122,101,41,44,32,100,116,121,112,101,61,
100,116,121,112,101,41,46,114,101,115,104,97,112,101,40,32,32,35,32,116,121,
112,101,58,32,105,103,110,111,114,101,10,
// '        #     sizes, order="F"\n
32,32,32,32,32,32,32,32,35,32,32,32,32,32,115,105,122,101,115,44,32,111,114,
100,101,114,61,34,70,34,10,
// '        # )\n
32,32,32,32,32,32,32,32,35,32,41,10,
// '        # print(type(arr))\n
32,32,32,32,32,32,32,32,35,32,112,114,105,110,116,40,116,121,112,101,40,97,114,
114,41,41,10,
// '\n
10,
// '        # # Convert the NumPy array to a CuPy array\n
32,32,32,32,32,32,32,32,35,32,35,32,67,111,110,118,101,114,116,32,116,104,101,
32,78,117,109,80,121,32,97,114,114,97,121,32,116,111,32,97,32,67,117,80,121,
32,97,114,114,97,121,10,
// '        # cp_arr = cp.array(np_arr, copy=False)\n
32,32,32,32,32,32,32,32,35,32,99,112,95,97,114,114,32,61,32,99,112,46,97,114,
114,97,121,40,110,112,95,97,114,114,44,32,99,111,112,121,61,70,97,108,115,101,
41,10,
// '        # print(type(cp_arr))\n
32,32,32,32,32,32,32,32,35,32,112,114,105,110,116,40,116,121,112,101,40,99,112,
95,97,114,114,41,41,10,
// '\n
10,
// '    return arr\n
32,32,32,32,114,101,116,117,114,110,32,97,114,114,10,
// '\n
10,
// '\n
10,
// 'def int_array_to_bool_array(int_array: NDArray) -> NDArray:\n
100,101,102,32,105,110,116,95,97,114,114,97,121,95,116,111,95,98,111,111,108,
95,97,114,114,97,121,40,105,110,116,95,97,114,114,97,121,58,32,78,68,65,114,
114,97,121,41,32,45,62,32,78,68,65,114,114,97,121,58,10,
// '    """\n
32,32,32,32,34,34,34,10,
// '    Converts a NumPy array of integers to a boolean array.\n
32,32,32,32,67,111,110,118,101,114,116,115,32,97,32,78,117,109,80,121,32,97,
114,114,97,121,32,111,102,32,105,110,116,101,103,101,114,115,32,116,111,32,97,
32,98,111,111,108,101,97,110,32,97,114,114,97,121,46,10,
// '    In the input array, 0 represents False, and any non-zero value (1 or -1) represents True.\n
32,32,32,32,73,110,32,116,104,101,32,105,110,112,117,116,32,97,114,114,97,121,
44,32,48,32,114,101,112,114,101,115,101,110,116,115,32,70,97,108,115,101,44,
32,97,110,100,32,97,110,121,32,110,111,110,45,122,101,114,111,32,118,97,108,
117,101,32,40,49,32,111,114,32,45,49,41,32,114,101,112,114,101,115,101,110,116,
115,32,84,114,117,101,46,10,
// '\n
10,
// '    Args:\n
32,32,32,32,65,114,103,115,58,10,
// '        int_array: A NumPy array of integers.\n
32,32,32,32,32,32,32,32,105,110,116,95,97,114,114,97,121,58,32,65,32,78,117,
109,80,121,32,97,114,114,97,121,32,111,102,32,105,110,116,101,103,101,114,115,
46,10,
// '\n
10,
// '    Returns:\n
32,32,32,32,82,101,116,117,114,110,115,58,10,
// '        A NumPy array of booleans.\n
32,32,32,32,32,32,32,32,65,32,78,117,109,80,121,32,97,114,114,97,121,32,111,
102,32,98,111,111,108,101,97,110,115,46,10,
// '    """\n
32,32,32,32,34,34,34,10,
// '    bool_array = int_array != 0\n
32,32,32,32,98,111,111,108,95,97,114,114,97,121,32,61,32,105,110,116,95,97,114,
114,97,121,32,33,61,32,48,10,
// '    return bool_array\n
32,32,32,32,114,101,116,117,114,110,32,98,111,111,108,95,97,114,114,97,121,10,
// '\n
10,
// '\n
10,
// 'def list_available_gpus():\n
100,101,102,32,108,105,115,116,95,97,118,97,105,108,97,98,108,101,95,103,112,
117,115,40,41,58,10,
// '    num_gpus = cp.cuda.runtime.getDeviceCount()\n
32,32,32,32,110,117,109,95,103,112,117,115,32,61,32,99,112,46,99,117,100,97,
46,114,117,110,116,105,109,101,46,103,101,116,68,101,118,105,99,101,67,111,117,
110,116,40,41,10,
// '    logging.debug("Total GPUs available: %d" % num_gpus)\n
32,32,32,32,108,111,103,103,105,110,103,46,100,101,98,117,103,40,34,84,111,116,
97,108,32,71,80,85,115,32,97,118,97,105,108,97,98,108,101,58,32,37,100,34,32,
37,32,110,117,109,95,103,112,117,115,41,10,
// '\n
10,
// '    for i in range(num_gpus):\n
32,32,32,32,102,111,114,32,105,32,105,110,32,114,97,110,103,101,40,110,117,109,
95,103,112,117,115,41,58,10,
// '        device = cp.cuda.Device(i)\n
32,32,32,32,32,32,32,32,100,101,118,105,99,101,32,61,32,99,112,46,99,117,100,
97,46,68,101,118,105,99,101,40,105,41,10,
// '        logging.debug(device)\n
32,32,32,32,32,32,32,32,108,111,103,103,105,110,103,46,100,101,98,117,103,40,
100,101,118,105,99,101,41,10,
// '\n
10,
// '\n
10,
// '@ffi.def_extern()\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,40,41,10,
// 'def identity_wrapper(inp: Field[[CellDim, KDim], float64], n_Cell: int32, n_K: int32):\n
100,101,102,32,105,100,101,110,116,105,116,121,95,119,114,97,112,112,101,114,
40,105,110,112,58,32,70,105,101,108,100,91,91,67,101,108,108,68,105,109,44,32,
75,68,105,109,93,44,32,102,108,111,97,116,54,52,93,44,32,110,95,67,101,108,108,
58,32,105,110,116,51,50,44,32,110,95,75,58,32,105,110,116,51,50,41,58,10,
// '    try:\n
32,32,32,32,116,114,121,58,10,
// '        logging.info("Python Execution Context Start")\n
32,32,32,32,32,32,32,32,108,111,103,103,105,110,103,46,105,110,102,111,40,34,
80,121,116,104,111,110,32,69,120,101,99,117,116,105,111,110,32,67,111,110,116,
101,120,116,32,83,116,97,114,116,34,41,10,
// '\n
10,
// '        list_available_gpus()\n
32,32,32,32,32,32,32,32,108,105,115,116,95,97,118,97,105,108,97,98,108,101,95,
103,112,117,115,40,41,10,
// '\n
10,
// '        # Unpack pointers into Ndarrays\n
32,32,32,32,32,32,32,32,35,32,85,110,112,97,99,107,32,112,111,105,110,116,101,
114,115,32,105,110,116,111,32,78,100,97,114,114,97,121,115,10,
// '\n
10,
// '        msg = "inp before unpacking: %s" % str(inp)\n
32,32,32,32,32,32,32,32,109,115,103,32,61,32,34,105,110,112,32,98,101,102,111,
114,101,32,117,110,112,97,99,107,105,110,103,58,32,37,115,34,32,37,32,115,116,
114,40,105,110,112,41,10,
// '        logging.debug(msg)\n
32,32,32,32,32,32,32,32,108,111,103,103,105,110,103,46,100,101,98,117,103,40,
109,115,103,41,10,
// '\n
10,
// '        inp = unpack_gpu(inp, n_Cell, n_K)\n
32,32,32,32,32,32,32,32,105,110,112,32,61,32,117,110,112,97,99,107,95,103,112,
117,40,105,110,112,44,32,110,95,67,101,108,108,44,32,110,95,75,41,10,
// '        msg = "inp after unpacking: %s" % str(inp)\n
32,32,32,32,32,32,32,32,109,115,103,32,61,32,34,105,110,112,32,97,102,116,101,
114,32,117,110,112,97,99,107,105,110,103,58,32,37,115,34,32,37,32,115,116,114,
40,105,110,112,41,10,
// '        logging.debug(msg)\n
32,32,32,32,32,32,32,32,108,111,103,103,105,110,103,46,100,101,98,117,103,40,
109,115,103,41,10,
// '        msg = "shape of inp after unpacking = %s" % str(inp.shape)\n
32,32,32,32,32,32,32,32,109,115,103,32,61,32,34,115,104,97,112,101,32,111,102,
32,105,110,112,32,97,102,116,101,114,32,117,110,112,97,99,107,105,110,103,32,
61,32,37,115,34,32,37,32,115,116,114,40,105,110,112,46,115,104,97,112,101,41,
10,
// '        logging.debug(msg)\n
32,32,32,32,32,32,32,32,108,111,103,103,105,110,103,46,100,101,98,117,103,40,
109,115,103,41,10,
// '\n
10,
// '        # Allocate GT4Py Fields\n
32,32,32,32,32,32,32,32,35,32,65,108,108,111,99,97,116,101,32,71,84,52,80,121,
32,70,105,101,108,100,115,10,
// '\n
10,
// '        inp = np_as_located_field(CellDim, KDim)(inp)\n
32,32,32,32,32,32,32,32,105,110,112,32,61,32,110,112,95,97,115,95,108,111,99,
97,116,101,100,95,102,105,101,108,100,40,67,101,108,108,68,105,109,44,32,75,
68,105,109,41,40,105,110,112,41,10,
// '        msg = "shape of inp after allocating as field = %s" % str(inp.shape)\n
32,32,32,32,32,32,32,32,109,115,103,32,61,32,34,115,104,97,112,101,32,111,102,
32,105,110,112,32,97,102,116,101,114,32,97,108,108,111,99,97,116,105,110,103,
32,97,115,32,102,105,101,108,100,32,61,32,37,115,34,32,37,32,115,116,114,40,
105,110,112,46,115,104,97,112,101,41,10,
// '        logging.debug(msg)\n
32,32,32,32,32,32,32,32,108,111,103,103,105,110,103,46,100,101,98,117,103,40,
109,115,103,41,10,
// '        msg = "inp after allocating as field: %s" % str(inp.ndarray)\n
32,32,32,32,32,32,32,32,109,115,103,32,61,32,34,105,110,112,32,97,102,116,101,
114,32,97,108,108,111,99,97,116,105,110,103,32,97,115,32,102,105,101,108,100,
58,32,37,115,34,32,37,32,115,116,114,40,105,110,112,46,110,100,97,114,114,97,
121,41,10,
// '        logging.debug(msg)\n
32,32,32,32,32,32,32,32,108,111,103,103,105,110,103,46,100,101,98,117,103,40,
109,115,103,41,10,
// '\n
10,
// '        identity(inp)\n
32,32,32,32,32,32,32,32,105,100,101,110,116,105,116,121,40,105,110,112,41,10,
// '\n
10,
// '        # debug info\n
32,32,32,32,32,32,32,32,35,32,100,101,98,117,103,32,105,110,102,111,10,
// '\n
10,
// '        msg = "shape of inp after computation = %s" % str(inp.shape)\n
32,32,32,32,32,32,32,32,109,115,103,32,61,32,34,115,104,97,112,101,32,111,102,
32,105,110,112,32,97,102,116,101,114,32,99,111,109,112,117,116,97,116,105,111,
110,32,61,32,37,115,34,32,37,32,115,116,114,40,105,110,112,46,115,104,97,112,
101,41,10,
// '        logging.debug(msg)\n
32,32,32,32,32,32,32,32,108,111,103,103,105,110,103,46,100,101,98,117,103,40,
109,115,103,41,10,
// '        msg = "inp after computation: %s" % str(inp.ndarray)\n
32,32,32,32,32,32,32,32,109,115,103,32,61,32,34,105,110,112,32,97,102,116,101,
114,32,99,111,109,112,117,116,97,116,105,111,110,58,32,37,115,34,32,37,32,115,
116,114,40,105,110,112,46,110,100,97,114,114,97,121,41,10,
// '        logging.debug(msg)\n
32,32,32,32,32,32,32,32,108,111,103,103,105,110,103,46,100,101,98,117,103,40,
109,115,103,41,10,
// '\n
10,
// '        logging.info("Python Execution Context End")\n
32,32,32,32,32,32,32,32,108,111,103,103,105,110,103,46,105,110,102,111,40,34,
80,121,116,104,111,110,32,69,120,101,99,117,116,105,111,110,32,67,111,110,116,
101,120,116,32,69,110,100,34,41,10,
// '\n
10,
// '    except Exception as e:\n
32,32,32,32,101,120,99,101,112,116,32,69,120,99,101,112,116,105,111,110,32,97,
115,32,101,58,10,
// '        logging.exception(f"A Python error occurred: {e}")\n
32,32,32,32,32,32,32,32,108,111,103,103,105,110,103,46,101,120,99,101,112,116,
105,111,110,40,102,34,65,32,80,121,116,104,111,110,32,101,114,114,111,114,32,
111,99,99,117,114,114,101,100,58,32,123,101,125,34,41,10,
// '        return 1\n
32,32,32,32,32,32,32,32,114,101,116,117,114,110,32,49,10,
// '\n
10,
// '    return 0\n
32,32,32,32,114,101,116,117,114,110,32,48,10,
0 };
#ifdef PYPY_VERSION
# define _CFFI_PYTHON_STARTUP_FUNC  _cffi_pypyinit_identity_plugin
#elif PY_MAJOR_VERSION >= 3
# define _CFFI_PYTHON_STARTUP_FUNC  PyInit_identity_plugin
#else
# define _CFFI_PYTHON_STARTUP_FUNC  initidentity_plugin
#endif

/***** Support code for embedding *****/

#ifdef __cplusplus
extern "C" {
#endif


#if defined(_WIN32)
#  define CFFI_DLLEXPORT  __declspec(dllexport)
#elif defined(__GNUC__)
#  define CFFI_DLLEXPORT  __attribute__((visibility("default")))
#else
#  define CFFI_DLLEXPORT  /* nothing */
#endif


/* There are two global variables of type _cffi_call_python_fnptr:

   * _cffi_call_python, which we declare just below, is the one called
     by ``extern "Python"`` implementations.

   * _cffi_call_python_org, which on CPython is actually part of the
     _cffi_exports[] array, is the function pointer copied from
     _cffi_backend.  If _cffi_start_python() fails, then this is set
     to NULL; otherwise, it should never be NULL.

   After initialization is complete, both are equal.  However, the
   first one remains equal to &_cffi_start_and_call_python until the
   very end of initialization, when we are (or should be) sure that
   concurrent threads also see a completely initialized world, and
   only then is it changed.
*/
#undef _cffi_call_python
typedef void (*_cffi_call_python_fnptr)(struct _cffi_externpy_s *, char *);
static void _cffi_start_and_call_python(struct _cffi_externpy_s *, char *);
static _cffi_call_python_fnptr _cffi_call_python = &_cffi_start_and_call_python;


#ifndef _MSC_VER
   /* --- Assuming a GCC not infinitely old --- */
# define cffi_compare_and_swap(l,o,n)  __sync_bool_compare_and_swap(l,o,n)
# define cffi_write_barrier()          __sync_synchronize()
# if !defined(__amd64__) && !defined(__x86_64__) &&   \
     !defined(__i386__) && !defined(__i386)
#   define cffi_read_barrier()         __sync_synchronize()
# else
#   define cffi_read_barrier()         (void)0
# endif
#else
   /* --- Windows threads version --- */
# include <Windows.h>
# define cffi_compare_and_swap(l,o,n) \
                               (InterlockedCompareExchangePointer(l,n,o) == (o))
# define cffi_write_barrier()       InterlockedCompareExchange(&_cffi_dummy,0,0)
# define cffi_read_barrier()           (void)0
static volatile LONG _cffi_dummy;
#endif

#ifdef WITH_THREAD
# ifndef _MSC_VER
#  include <pthread.h>
   static pthread_mutex_t _cffi_embed_startup_lock;
# else
   static CRITICAL_SECTION _cffi_embed_startup_lock;
# endif
  static char _cffi_embed_startup_lock_ready = 0;
#endif

static void _cffi_acquire_reentrant_mutex(void)
{
    static void *volatile lock = NULL;

    while (!cffi_compare_and_swap(&lock, NULL, (void *)1)) {
        /* should ideally do a spin loop instruction here, but
           hard to do it portably and doesn't really matter I
           think: pthread_mutex_init() should be very fast, and
           this is only run at start-up anyway. */
    }

#ifdef WITH_THREAD
    if (!_cffi_embed_startup_lock_ready) {
# ifndef _MSC_VER
        pthread_mutexattr_t attr;
        pthread_mutexattr_init(&attr);
        pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
        pthread_mutex_init(&_cffi_embed_startup_lock, &attr);
# else
        InitializeCriticalSection(&_cffi_embed_startup_lock);
# endif
        _cffi_embed_startup_lock_ready = 1;
    }
#endif

    while (!cffi_compare_and_swap(&lock, (void *)1, NULL))
        ;

#ifndef _MSC_VER
    pthread_mutex_lock(&_cffi_embed_startup_lock);
#else
    EnterCriticalSection(&_cffi_embed_startup_lock);
#endif
}

static void _cffi_release_reentrant_mutex(void)
{
#ifndef _MSC_VER
    pthread_mutex_unlock(&_cffi_embed_startup_lock);
#else
    LeaveCriticalSection(&_cffi_embed_startup_lock);
#endif
}


/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION

#ifndef CFFI_MESSAGEBOX
# ifdef _MSC_VER
#  define CFFI_MESSAGEBOX  1
# else
#  define CFFI_MESSAGEBOX  0
# endif
#endif


#if CFFI_MESSAGEBOX
/* Windows only: logic to take the Python-CFFI embedding logic
   initialization errors and display them in a background thread
   with MessageBox.  The idea is that if the whole program closes
   as a result of this problem, then likely it is already a console
   program and you can read the stderr output in the console too.
   If it is not a console program, then it will likely show its own
   dialog to complain, or generally not abruptly close, and for this
   case the background thread should stay alive.
*/
static void *volatile _cffi_bootstrap_text;

static PyObject *_cffi_start_error_capture(void)
{
    PyObject *result = NULL;
    PyObject *x, *m, *bi;

    if (InterlockedCompareExchangePointer(&_cffi_bootstrap_text,
            (void *)1, NULL) != NULL)
        return (PyObject *)1;

    m = PyImport_AddModule("_cffi_error_capture");
    if (m == NULL)
        goto error;

    result = PyModule_GetDict(m);
    if (result == NULL)
        goto error;

#if PY_MAJOR_VERSION >= 3
    bi = PyImport_ImportModule("builtins");
#else
    bi = PyImport_ImportModule("__builtin__");
#endif
    if (bi == NULL)
        goto error;
    PyDict_SetItemString(result, "__builtins__", bi);
    Py_DECREF(bi);

    x = PyRun_String(
        "import sys\n"
        "class FileLike:\n"
        "  def write(self, x):\n"
        "    try:\n"
        "      of.write(x)\n"
        "    except: pass\n"
        "    self.buf += x\n"
        "  def flush(self):\n"
        "    pass\n"
        "fl = FileLike()\n"
        "fl.buf = ''\n"
        "of = sys.stderr\n"
        "sys.stderr = fl\n"
        "def done():\n"
        "  sys.stderr = of\n"
        "  return fl.buf\n",   /* make sure the returned value stays alive */
        Py_file_input,
        result, result);
    Py_XDECREF(x);

 error:
    if (PyErr_Occurred())
    {
        PyErr_WriteUnraisable(Py_None);
        PyErr_Clear();
    }
    return result;
}

#pragma comment(lib, "user32.lib")

static DWORD WINAPI _cffi_bootstrap_dialog(LPVOID ignored)
{
    Sleep(666);    /* may be interrupted if the whole process is closing */
#if PY_MAJOR_VERSION >= 3
    MessageBoxW(NULL, (wchar_t *)_cffi_bootstrap_text,
                L"Python-CFFI error",
                MB_OK | MB_ICONERROR);
#else
    MessageBoxA(NULL, (char *)_cffi_bootstrap_text,
                "Python-CFFI error",
                MB_OK | MB_ICONERROR);
#endif
    _cffi_bootstrap_text = NULL;
    return 0;
}

static void _cffi_stop_error_capture(PyObject *ecap)
{
    PyObject *s;
    void *text;

    if (ecap == (PyObject *)1)
        return;

    if (ecap == NULL)
        goto error;

    s = PyRun_String("done()", Py_eval_input, ecap, ecap);
    if (s == NULL)
        goto error;

    /* Show a dialog box, but in a background thread, and
       never show multiple dialog boxes at once. */
#if PY_MAJOR_VERSION >= 3
    text = PyUnicode_AsWideCharString(s, NULL);
#else
    text = PyString_AsString(s);
#endif

    _cffi_bootstrap_text = text;

    if (text != NULL)
    {
        HANDLE h;
        h = CreateThread(NULL, 0, _cffi_bootstrap_dialog,
                         NULL, 0, NULL);
        if (h != NULL)
            CloseHandle(h);
    }
    /* decref the string, but it should stay alive as 'fl.buf'
       in the small module above.  It will really be freed only if
       we later get another similar error.  So it's a leak of at
       most one copy of the small module.  That's fine for this
       situation which is usually a "fatal error" anyway. */
    Py_DECREF(s);
    PyErr_Clear();
    return;

  error:
    _cffi_bootstrap_text = NULL;
    PyErr_Clear();
}

#else

static PyObject *_cffi_start_error_capture(void) { return NULL; }
static void _cffi_stop_error_capture(PyObject *ecap) { }

#endif


#define _cffi_call_python_org  _cffi_exports[_CFFI_CPIDX]

PyMODINIT_FUNC _CFFI_PYTHON_STARTUP_FUNC(void);   /* forward */

static void _cffi_py_initialize(void)
{
    /* XXX use initsigs=0, which "skips initialization registration of
       signal handlers, which might be useful when Python is
       embedded" according to the Python docs.  But review and think
       if it should be a user-controllable setting.

       XXX we should also give a way to write errors to a buffer
       instead of to stderr.

       XXX if importing 'site' fails, CPython (any version) calls
       exit().  Should we try to work around this behavior here?
    */
    Py_InitializeEx(0);
}

static int _cffi_initialize_python(void)
{
    /* This initializes Python, imports _cffi_backend, and then the
       present .dll/.so is set up as a CPython C extension module.
    */
    int result;
    PyGILState_STATE state;
    PyObject *pycode=NULL, *global_dict=NULL, *x;
    PyObject *builtins;

    state = PyGILState_Ensure();

    /* Call the initxxx() function from the present module.  It will
       create and initialize us as a CPython extension module, instead
       of letting the startup Python code do it---it might reimport
       the same .dll/.so and get maybe confused on some platforms.
       It might also have troubles locating the .dll/.so again for all
       I know.
    */
    (void)_CFFI_PYTHON_STARTUP_FUNC();
    if (PyErr_Occurred())
        goto error;

    /* Now run the Python code provided to ffi.embedding_init_code().
     */
    pycode = Py_CompileString(_CFFI_PYTHON_STARTUP_CODE,
                              "<init code for '" _CFFI_MODULE_NAME "'>",
                              Py_file_input);
    if (pycode == NULL)
        goto error;
    global_dict = PyDict_New();
    if (global_dict == NULL)
        goto error;
    builtins = PyEval_GetBuiltins();
    if (builtins == NULL)
        goto error;
    if (PyDict_SetItemString(global_dict, "__builtins__", builtins) < 0)
        goto error;
    x = PyEval_EvalCode(
#if PY_MAJOR_VERSION < 3
                        (PyCodeObject *)
#endif
                        pycode, global_dict, global_dict);
    if (x == NULL)
        goto error;
    Py_DECREF(x);

    /* Done!  Now if we've been called from
       _cffi_start_and_call_python() in an ``extern "Python"``, we can
       only hope that the Python code did correctly set up the
       corresponding @ffi.def_extern() function.  Otherwise, the
       general logic of ``extern "Python"`` functions (inside the
       _cffi_backend module) will find that the reference is still
       missing and print an error.
     */
    result = 0;
 done:
    Py_XDECREF(pycode);
    Py_XDECREF(global_dict);
    PyGILState_Release(state);
    return result;

 error:;
    {
        /* Print as much information as potentially useful.
           Debugging load-time failures with embedding is not fun
        */
        PyObject *ecap;
        PyObject *exception, *v, *tb, *f, *modules, *mod;
        PyErr_Fetch(&exception, &v, &tb);
        ecap = _cffi_start_error_capture();
        f = PySys_GetObject((char *)"stderr");
        if (f != NULL && f != Py_None) {
            PyFile_WriteString(
                "Failed to initialize the Python-CFFI embedding logic:\n\n", f);
        }

        if (exception != NULL) {
            PyErr_NormalizeException(&exception, &v, &tb);
            PyErr_Display(exception, v, tb);
        }
        Py_XDECREF(exception);
        Py_XDECREF(v);
        Py_XDECREF(tb);

        if (f != NULL && f != Py_None) {
            PyFile_WriteString("\nFrom: " _CFFI_MODULE_NAME
                               "\ncompiled with cffi version: 1.16.0"
                               "\n_cffi_backend module: ", f);
            modules = PyImport_GetModuleDict();
            mod = PyDict_GetItemString(modules, "_cffi_backend");
            if (mod == NULL) {
                PyFile_WriteString("not loaded", f);
            }
            else {
                v = PyObject_GetAttrString(mod, "__file__");
                PyFile_WriteObject(v, f, 0);
                Py_XDECREF(v);
            }
            PyFile_WriteString("\nsys.path: ", f);
            PyFile_WriteObject(PySys_GetObject((char *)"path"), f, 0);
            PyFile_WriteString("\n\n", f);
        }
        _cffi_stop_error_capture(ecap);
    }
    result = -1;
    goto done;
}

#if PY_VERSION_HEX < 0x03080000
PyAPI_DATA(char *) _PyParser_TokenNames[];  /* from CPython */
#endif

static int _cffi_carefully_make_gil(void)
{
    /* This does the basic initialization of Python.  It can be called
       completely concurrently from unrelated threads.  It assumes
       that we don't hold the GIL before (if it exists), and we don't
       hold it afterwards.

       (What it really does used to be completely different in Python 2
       and Python 3, with the Python 2 solution avoiding the spin-lock
       around the Py_InitializeEx() call.  However, after recent changes
       to CPython 2.7 (issue #358) it no longer works.  So we use the
       Python 3 solution everywhere.)

       This initializes Python by calling Py_InitializeEx().
       Important: this must not be called concurrently at all.
       So we use a global variable as a simple spin lock.  This global
       variable must be from 'libpythonX.Y.so', not from this
       cffi-based extension module, because it must be shared from
       different cffi-based extension modules.

       In Python < 3.8, we choose
       _PyParser_TokenNames[0] as a completely arbitrary pointer value
       that is never written to.  The default is to point to the
       string "ENDMARKER".  We change it temporarily to point to the
       next character in that string.  (Yes, I know it's REALLY
       obscure.)

       In Python >= 3.8, this string array is no longer writable, so
       instead we pick PyCapsuleType.tp_version_tag.  We can't change
       Python < 3.8 because someone might use a mixture of cffi
       embedded modules, some of which were compiled before this file
       changed.

       In Python >= 3.12, this stopped working because that particular
       tp_version_tag gets modified during interpreter startup.  It's
       arguably a bad idea before 3.12 too, but again we can't change
       that because someone might use a mixture of cffi embedded
       modules, and no-one reported a bug so far.  In Python >= 3.12
       we go instead for PyCapsuleType.tp_as_buffer, which is supposed
       to always be NULL.  We write to it temporarily a pointer to
       a struct full of NULLs, which is semantically the same.
    */

#ifdef WITH_THREAD
# if PY_VERSION_HEX < 0x03080000
    char *volatile *lock = (char *volatile *)_PyParser_TokenNames;
    char *old_value, *locked_value;

    while (1) {    /* spin loop */
        old_value = *lock;
        locked_value = old_value + 1;
        if (old_value[0] == 'E') {
            assert(old_value[1] == 'N');
            if (cffi_compare_and_swap(lock, old_value, locked_value))
                break;
        }
        else {
            assert(old_value[0] == 'N');
            /* should ideally do a spin loop instruction here, but
               hard to do it portably and doesn't really matter I
               think: PyEval_InitThreads() should be very fast, and
               this is only run at start-up anyway. */
        }
    }
# else
#  if PY_VERSION_HEX < 0x030C0000
    int volatile *lock = (int volatile *)&PyCapsule_Type.tp_version_tag;
    int old_value, locked_value = -42;
    assert(!(PyCapsule_Type.tp_flags & Py_TPFLAGS_HAVE_VERSION_TAG));
#  else
    static struct ebp_s { PyBufferProcs buf; int mark; } empty_buffer_procs;
    empty_buffer_procs.mark = -42;
    PyBufferProcs *volatile *lock = (PyBufferProcs *volatile *)
        &PyCapsule_Type.tp_as_buffer;
    PyBufferProcs *old_value, *locked_value = &empty_buffer_procs.buf;
#  endif

    while (1) {    /* spin loop */
        old_value = *lock;
        if (old_value == 0) {
            if (cffi_compare_and_swap(lock, old_value, locked_value))
                break;
        }
        else {
#  if PY_VERSION_HEX < 0x030C0000
            assert(old_value == locked_value);
#  else
            /* The pointer should point to a possibly different
               empty_buffer_procs from another C extension module */
            assert(((struct ebp_s *)old_value)->mark == -42);
#  endif
            /* should ideally do a spin loop instruction here, but
               hard to do it portably and doesn't really matter I
               think: PyEval_InitThreads() should be very fast, and
               this is only run at start-up anyway. */
        }
    }
# endif
#endif

    /* call Py_InitializeEx() */
    if (!Py_IsInitialized()) {
        _cffi_py_initialize();
#if PY_VERSION_HEX < 0x03070000
        PyEval_InitThreads();
#endif
        PyEval_SaveThread();  /* release the GIL */
        /* the returned tstate must be the one that has been stored into the
           autoTLSkey by _PyGILState_Init() called from Py_Initialize(). */
    }
    else {
#if PY_VERSION_HEX < 0x03070000
        /* PyEval_InitThreads() is always a no-op from CPython 3.7 */
        PyGILState_STATE state = PyGILState_Ensure();
        PyEval_InitThreads();
        PyGILState_Release(state);
#endif
    }

#ifdef WITH_THREAD
    /* release the lock */
    while (!cffi_compare_and_swap(lock, locked_value, old_value))
        ;
#endif

    return 0;
}

/**********  end CPython-specific section  **********/


#else


/**********  PyPy-specific section  **********/

PyMODINIT_FUNC _CFFI_PYTHON_STARTUP_FUNC(const void *[]);   /* forward */

static struct _cffi_pypy_init_s {
    const char *name;
    void *func;    /* function pointer */
    const char *code;
} _cffi_pypy_init = {
    _CFFI_MODULE_NAME,
    _CFFI_PYTHON_STARTUP_FUNC,
    _CFFI_PYTHON_STARTUP_CODE,
};

extern int pypy_carefully_make_gil(const char *);
extern int pypy_init_embedded_cffi_module(int, struct _cffi_pypy_init_s *);

static int _cffi_carefully_make_gil(void)
{
    return pypy_carefully_make_gil(_CFFI_MODULE_NAME);
}

static int _cffi_initialize_python(void)
{
    return pypy_init_embedded_cffi_module(0xB011, &_cffi_pypy_init);
}

/**********  end PyPy-specific section  **********/


#endif


#ifdef __GNUC__
__attribute__((noinline))
#endif
static _cffi_call_python_fnptr _cffi_start_python(void)
{
    /* Delicate logic to initialize Python.  This function can be
       called multiple times concurrently, e.g. when the process calls
       its first ``extern "Python"`` functions in multiple threads at
       once.  It can also be called recursively, in which case we must
       ignore it.  We also have to consider what occurs if several
       different cffi-based extensions reach this code in parallel
       threads---it is a different copy of the code, then, and we
       can't have any shared global variable unless it comes from
       'libpythonX.Y.so'.

       Idea:

       * _cffi_carefully_make_gil(): "carefully" call
         PyEval_InitThreads() (possibly with Py_InitializeEx() first).

       * then we use a (local) custom lock to make sure that a call to this
         cffi-based extension will wait if another call to the *same*
         extension is running the initialization in another thread.
         It is reentrant, so that a recursive call will not block, but
         only one from a different thread.

       * then we grab the GIL and (Python 2) we call Py_InitializeEx().
         At this point, concurrent calls to Py_InitializeEx() are not
         possible: we have the GIL.

       * do the rest of the specific initialization, which may
         temporarily release the GIL but not the custom lock.
         Only release the custom lock when we are done.
    */
    static char called = 0;

    if (_cffi_carefully_make_gil() != 0)
        return NULL;

    _cffi_acquire_reentrant_mutex();

    /* Here the GIL exists, but we don't have it.  We're only protected
       from concurrency by the reentrant mutex. */

    /* This file only initializes the embedded module once, the first
       time this is called, even if there are subinterpreters. */
    if (!called) {
        called = 1;  /* invoke _cffi_initialize_python() only once,
                        but don't set '_cffi_call_python' right now,
                        otherwise concurrent threads won't call
                        this function at all (we need them to wait) */
        if (_cffi_initialize_python() == 0) {
            /* now initialization is finished.  Switch to the fast-path. */

            /* We would like nobody to see the new value of
               '_cffi_call_python' without also seeing the rest of the
               data initialized.  However, this is not possible.  But
               the new value of '_cffi_call_python' is the function
               'cffi_call_python()' from _cffi_backend.  So:  */
            cffi_write_barrier();
            /* ^^^ we put a write barrier here, and a corresponding
               read barrier at the start of cffi_call_python().  This
               ensures that after that read barrier, we see everything
               done here before the write barrier.
            */

            assert(_cffi_call_python_org != NULL);
            _cffi_call_python = (_cffi_call_python_fnptr)_cffi_call_python_org;
        }
        else {
            /* initialization failed.  Reset this to NULL, even if it was
               already set to some other value.  Future calls to
               _cffi_start_python() are still forced to occur, and will
               always return NULL from now on. */
            _cffi_call_python_org = NULL;
        }
    }

    _cffi_release_reentrant_mutex();

    return (_cffi_call_python_fnptr)_cffi_call_python_org;
}

static
void _cffi_start_and_call_python(struct _cffi_externpy_s *externpy, char *args)
{
    _cffi_call_python_fnptr fnptr;
    int current_err = errno;
#ifdef _MSC_VER
    int current_lasterr = GetLastError();
#endif
    fnptr = _cffi_start_python();
    if (fnptr == NULL) {
        fprintf(stderr, "function %s() called, but initialization code "
                        "failed.  Returning 0.\n", externpy->name);
        memset(args, 0, externpy->size_of_result);
    }
#ifdef _MSC_VER
    SetLastError(current_lasterr);
#endif
    errno = current_err;

    if (fnptr != NULL)
        fnptr(externpy, args);
}


/* The cffi_start_python() function makes sure Python is initialized
   and our cffi module is set up.  It can be called manually from the
   user C code.  The same effect is obtained automatically from any
   dll-exported ``extern "Python"`` function.  This function returns
   -1 if initialization failed, 0 if all is OK.  */
_CFFI_UNUSED_FN
static int cffi_start_python(void)
{
    if (_cffi_call_python == &_cffi_start_and_call_python) {
        if (_cffi_start_python() == NULL)
            return -1;
    }
    cffi_read_barrier();
    return 0;
}

#undef cffi_compare_and_swap
#undef cffi_write_barrier
#undef cffi_read_barrier

#ifdef __cplusplus
}
#endif

/************************************************************/

#include "identity_plugin.h"

/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 2), // int()(void *, int, int)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 6), // void *
/*  2 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/*  3 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/*  4 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  5 */ _CFFI_OP(_CFFI_OP_POINTER, 0), // int(*)(void *, int, int)
/*  6 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static struct _cffi_externpy_s _cffi_externpy__identity_wrapper =
  { "identity_plugin.identity_wrapper", (int)sizeof(int), 0, 0 };

CFFI_DLLEXPORT int identity_wrapper(void * a0, int a1, int a2)
{
  char a[24];
  char *p = a;
  *(void * *)(p + 0) = a0;
  *(int *)(p + 8) = a1;
  *(int *)(p + 16) = a2;
  _cffi_call_python(&_cffi_externpy__identity_wrapper, p);
  return *(int *)p;
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "identity_wrapper", (void *)&_cffi_externpy__identity_wrapper, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 5), (void *)identity_wrapper },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  NULL,  /* no fields */
  NULL,  /* no struct_unions */
  NULL,  /* no enums */
  NULL,  /* no typenames */
  1,  /* num_globals */
  0,  /* num_struct_unions */
  0,  /* num_enums */
  0,  /* num_typenames */
  NULL,  /* no includes */
  7,  /* num_types */
  1,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_identity_plugin(const void *p[])
{
    if (((intptr_t)p[0]) >= 0x0A03) {
        _cffi_call_python_org = (void(*)(struct _cffi_externpy_s *, char *))p[1];
    }
    p[0] = (const void *)0x2701;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_identity_plugin(void) { return NULL; }
#  else
     initidentity_plugin(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_identity_plugin(void)
{
  return _cffi_init("identity_plugin", 0x2701, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initidentity_plugin(void)
{
  _cffi_init("identity_plugin", 0x2701, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
