[build-system]
requires = ["setuptools>=58.0.4", "wheel>=0.37.0"]
build-backend = "setuptools.build_meta"

[project]
name = "icon4py-dycore"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["src"]
