include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build
  - test
  - benchmark

.py310: &py310
  PYVERSION_PREFIX: py310
  PYVERSION: 3.10.9

variables:
  PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/icon4py:$CI_COMMIT_SHORT_SHA
  PYTHON_VERSION: "3.10"

.build_template:
  stage: build
  extends: .container-builder
  variables:
    DOCKERFILE: ci/docker/Dockerfile.build
    DOCKER_BUILD_ARGS: '["PYVERSION=$PYVERSION"]'
    <<: *py310

.test_template:
  extends: .container-runner-daint-gpu
  timeout: 8h
  image: $PERSIST_IMAGE_NAME
  before_script:
    - apt-get update
    - python3 -m pip install --upgrade pip setuptools wheel
    - cd /icon4py
    - pyversion_no_dot="${PYTHON_VERSION//./}"
    - pip install tox clang-format
    - python -c "import cupy"
  variables:
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1
    SLURM_TIMELIMIT: '06:00:00'
    CRAY_CUDA_MPS: 1
    NUM_PROCESSES: auto
    VIRTUALENV_SYSTEM_SITE_PACKAGES: 1

build_job:
  extends: .build_template

test_model_job_roundtrip_simple_grid:
  extends: .test_template
  stage: test
  script:
    - tox -r -c model/ --verbose -- --benchmark-skip -n auto

test_model_job_gtfn_cpu_simple_grid:
  extends: .test_template
  stage: test
  script:
    - tox -r -e stencil_tests -c model/ --verbose -- --benchmark-skip -n auto --backend=gtfn_cpu

test_model_job_gtfn_gpu_simple_grid:
  extends: .test_template
  stage: test
  script:
    - tox -r -e stencil_tests -c model/ --verbose -- --benchmark-skip -n auto --backend=gtfn_gpu

test_tools_job:
  extends: .test_template
  stage: test
  script:
    - tox -r -c tools/ --verbose

benchmark_model_gtfn_cpu_simple_grid:
  extends: .test_template
  stage: benchmark
  script:
      - tox -r -e stencil_tests -c model/ --verbose -- --benchmark-only --backend=gtfn_cpu --grid=simple_grid

benchmark_model_gtfn_gpu_simple_grid:
  extends: .test_template
  stage: benchmark
  script:
    - tox -r -e stencil_tests -c model/ --verbose -- --benchmark-only --backend=gtfn_gpu --grid=simple_grid
