include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build
  - test_model
  - test_tools

variables:
  PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/icon4py:$CI_COMMIT_SHORT_SHA
  PYTHON_VERSION: "3.10"

.build_template:
  stage: build
  extends: .container-builder
  variables:
    DOCKERFILE: ci/docker/Dockerfile.build

.test_template:
  extends: .container-runner-hohgant-a100
  image: $PERSIST_IMAGE_NAME
  before_script:
    - apt-get update
    - python3 -m pip install --upgrade pip setuptools wheel
    - cd /icon4py
    - pyversion_no_dot="${PYTHON_VERSION//./}"
    - pip install tox clang-format
  variables:
    SLURM_JOB_NUM_NODES: 2
    SLURM_NTASKS: 2

build_job:
  extends: .build_template

test_model_job:
  extends: .test_template
  stage: test_model
  script:   # TODO: once gtfn backends work parametrise with backend
    - ENABLE_BENCHMARKS= tox -r -e py${pyversion_no_dot} -c model/ --verbose

test_tools_job:
  extends: .test_template
  stage: test_tools
  script:
    - tox -r -e py${pyversion_no_dot} -c tools/ --verbose
