include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build
  - test
  - benchmark

variables:
  PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/icon4py:$CI_COMMIT_SHORT_SHA
  PYTHON_VERSION: "3.10"

.build_template:
  stage: build
  extends: .container-builder
  variables:
    DOCKERFILE: ci/docker/Dockerfile.build

.test_template:
  extends: .container-runner-clariden-a100
  timeout: 2h
  image: $PERSIST_IMAGE_NAME
  before_script:
    - apt-get update
    - python3 -m pip install --upgrade pip setuptools wheel
    - cd /icon4py
    - pyversion_no_dot="${PYTHON_VERSION//./}"
    - pip install tox clang-format
  variables:
    SLURM_JOB_NUM_NODES: 2
    SLURM_NTASKS: 2
    SLURM_TIMELIMIT: '02:00:00'

build_job:
  extends: .build_template

test_model_job_embedded_simple_grid:
  extends: .test_template
  stage: test
  script:
    - tox -r -e py${pyversion_no_dot} -c model/ --verbose -- --benchmark-skip -n auto

benchmark_model_gtfn_cpu_simple_grid:
  extends: .test_template
  stage: benchmark
  script:
    - tox -r -e py${pyversion_no_dot} -c model/ --verbose -- --benchmark-only --backend=gtfn_cpu --grid=simple_grid

test_tools_job:
  extends: .test_template
  stage: test
  script:
    - tox -r -e py${pyversion_no_dot} -c tools/ --verbose
