include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build
  - test

variables:
  PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/icon4py:$CI_COMMIT_SHORT_SHA
  PYTHON_VERSION: "3.10"

build_job:
  stage: build
  extends: .container-builder
  variables:
    DOCKERFILE: ci/docker/Dockerfile.build

test_job:
  stage: test
  extends: .container-runner-hohgant-a100
  image: $PERSIST_IMAGE_NAME
  before_script:
    - apt-get update
    - apt-get install -y libboost-all-dev
    - python -m pip install --upgrade pip setuptools wheel
  script:
    - pyversion_no_dot="${PYTHON_VERSION//./}"
    - pip install tox clang-format
    - tox -r -e py${pyversion_no_dot} -c model/
  variables:
    SLURM_JOB_NUM_NODES: 2
    SLURM_NTASKS: 2
