include:
  - local: 'ci/base.yml'

.test_model_stencils:
  stage: test
  variables:
    SLURM_TIMELIMIT: '00:10:00'
  script:
    - nox -s "test_model-3.10(stencils, $COMPONENT)" -- --backend=$BACKEND --grid=$GRID
  rules:
    - if: $COMPONENT == 'dycore' || $COMPONENT == 'diffusion'
      variables:
        SLURM_TIMELIMIT: '00:20:00'
    - when: on_success
  parallel:
    matrix:
    - COMPONENT: [diffusion, dycore, microphysics, common, driver]
      BACKEND: [gtfn_gpu]
      GRID: [simple_grid, icon_grid]
# test_model_stencils_x86_64:
#   extends: [.test_model_stencils, .test_template_x86_64]
test_model_stencils_aarch64:
  extends: [.test_model_stencils, .test_template_aarch64]


.test_tools_datatests:
  stage: test
  script:
    - nox -s 'test_tools-3.10(datatest)'
# test_tools_x86_64:
#   extends: [.test_tools_datatests, .test_template_x86_64]
test_tools_datatests_aarch64:
  extends: [.test_tools_datatests, .test_template_aarch64]

.test_model_datatests:
  stage: test
  variables:
    SLURM_TIMELIMIT: '00:30:00'
  script:
    - nox -s "test_model-3.10(datatest, $COMPONENT)" -- --backend=$BACKEND --level=$LEVEL
  rules:
    - if: $COMPONENT == 'common' && $BACKEND == 'gtfn_gpu' && $LEVEL == 'integration'
      variables:
        SLURM_TIMELIMIT: '01:30:00'
    - if: $BACKEND == 'embedded'
      variables:
        SLURM_TIMELIMIT: '00:15:00'
    - when: on_success
  parallel:
    matrix:
    - COMPONENT: [advection, diffusion, dycore, microphysics, common, driver]
      BACKEND: [embedded, gtfn_cpu, gtfn_gpu]
      LEVEL: [integration]
# test_model_datatests_x86_64:
#   extends: [.test_model_datatests, .test_template_x86_64]
test_model_datatests_aarch64:
  extends: [.test_model_datatests, .test_template_aarch64]

