include:
  - local: 'ci/base.yml'

.test_model_stencils:
  stage: test
  script:
    - nox -s test_model_stencils-3.10 -- --backend=$BACKEND --grid=$GRID
  parallel:
    matrix:
    - BACKEND: [gtfn_cpu, gtfn_gpu, roundtrip]
      GRID: [simple_grid, icon_grid]
  rules:
    # exclude slow test configurations
    - if: $BACKEND == "roundtrip" && $GRID == "icon_grid"
      when: never
    - when: on_success
# test_model_stencils_x86_64:
#   extends: [.test_model_stencils, .test_template_x86_64]
test_model_stencils_aarch64:
  extends: [.test_model_stencils, .test_template_aarch64]

.test_tools:
  stage: test
  script:
    - nox -s 'test_tools-3.10'
# test_tools_x86_64:
#   extends: [.test_tools, .test_template_x86_64]
test_tools_aarch64:
  extends: [.test_tools, .test_template_aarch64]

.test_model_datatests:
  stage: test
  script:
    - nox -s "test_model_datatest-3.10(subpackage='$COMPONENT')" -- --backend=$BACKEND 
  parallel:
    matrix:
    - COMPONENT: [atmosphere/advection, atmosphere/diffusion, atmosphere/dycore, atmosphere/subgrid_scale_physics/microphysics, common, driver]
      BACKEND: [gtfn_cpu, gtfn_gpu]
# test_model_datatests_x86_64:
#   extends: [.test_model_datatests, .test_template_x86_64]
test_model_datatests_aarch64:
  extends: [.test_model_datatests, .test_template_aarch64]
