include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'
  - local: 'base.yml'

build:
  extends: .build_template

test_model_simple_grid:
    extends: .test_template
    stage: test
    script:
      - tox -r -e run_stencil_tests -c model/ --verbose -- --backend=$BACKEND
    parallel:
      matrix:
        - BACKEND: [gtfn_cpu, gtfn_gpu, roundtrip]

test_tools:
  extends: .test_template
  stage: test
  script:
    - tox -r -c tools/ --verbose
