include:
  - local: 'ci/base.yml'

.test_model_stencils:
  stage: test
  script:
    - nox -s "test_model-3.10(stencils, $COMPONENT)" -- --backend=$BACKEND --grid=$GRID
  rules:
    - if: $BACKEND == 'dace_gpu' || $BACKEND == 'gtfn_gpu'
      variables:
        NUM_PROCESSES: 8
        SLURM_TIMELIMIT: '01:00:00'
    - when: on_success
      variables:
        SLURM_TIMELIMIT: '01:00:00'
  parallel:
    matrix:
      - COMPONENT: [all]
        BACKEND: [gtfn_gpu]
        GRID: [simple, icon_regional]
# test_model_stencils_x86_64:
#   extends: [.test_model_stencils, .test_template_x86_64]
test_model_stencils_aarch64:
  extends: [.test_model_stencils, .test_template_aarch64]


.test_tools_datatests:
  stage: test
  script:
    - nox -s 'test_tools-3.10(datatest)'
# test_tools_x86_64:
#   extends: [.test_tools_datatests, .test_template_x86_64]
test_tools_datatests_aarch64:
  extends: [.test_tools_datatests, .test_template_aarch64]

.test_model_datatests:
  stage: test
  script:
    - nox -s "test_model-3.10(datatest, $COMPONENT)" -- --backend=$BACKEND --level=$LEVEL
  rules:
    - if: $BACKEND == 'dace_gpu' || $BACKEND == 'gtfn_gpu'
      variables:
        NUM_PROCESSES: 8
        SLURM_TIMELIMIT: '01:00:00'
    - when: on_success
      variables:
        SLURM_TIMELIMIT: '01:00:00'
  parallel:
    matrix:
      - COMPONENT: [all]
        BACKEND: [embedded, dace_gpu, gtfn_cpu, gtfn_gpu]
        LEVEL: [integration]
# test_model_datatests_x86_64:
#   extends: [.test_model_datatests, .test_template_x86_64]
test_model_datatests_aarch64:
  extends: [.test_model_datatests, .test_template_aarch64]
