include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - baseimage
  - image
  - build
  - test
  - benchmark

variables:
  PYVERSION_PREFIX: py310
  PYVERSION: 3.10.9

# Base image build step with SHA256 checksum for caching
.build_distributed_baseimage:
  stage: baseimage
  before_script:
    # include build arguments in hash since we use a parameterized Docker file
    - DOCKER_TAG=`echo "$(cat $DOCKERFILE) $DOCKER_BUILD_ARGS" | sha256sum | head -c 16`
    - export PERSIST_IMAGE_NAME=$CSCS_REGISTRY_PATH/public/$ARCH/base/icon4py:$DOCKER_TAG-$PYVERSION-mpi
    - echo "BASE_IMAGE_${PYVERSION_PREFIX}=$PERSIST_IMAGE_NAME" >> build.env
  artifacts:
    reports:
      dotenv: build.env
  variables:
    DOCKERFILE: ci/docker/base_mpi.Dockerfile
    # change to 'always' if you want to rebuild, even if target tag exists already (if-not-exists is the default, i.e. we could also skip the variable)
    CSCS_REBUILD_POLICY: if-not-exists

build_distributed_baseimage_aarch64:
  extends: [.container-builder-cscs-gh200, .build_distributed_baseimage]
  variables:
    DOCKER_BUILD_ARGS: '["ARCH=$ARCH", "PYVERSION=$PYVERSION"]'

.build_distributed_template:
  variables:
    DOCKERFILE: ci/docker/checkout_mpi.Dockerfile
    DOCKER_BUILD_ARGS: '["PYVERSION=$PYVERSION", "BASE_IMAGE=${BASE_IMAGE_${PYVERSION_PREFIX}}", "VENV=${UV_PROJECT_ENVIRONMENT}"]'
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/public/$ARCH/icon4py/icon4py-ci:$CI_COMMIT_SHA-$UV_PROJECT_ENVIRONMENT-$PYVERSION-mpi

.build_distributed_cpu:
  extends: [.build_distributed_template]
  variables:
    UV_PROJECT_ENVIRONMENT: venv_dist

build_distributed_cpu:
  stage: image
  extends: [.container-builder-cscs-gh200, .build_distributed_cpu]
  needs: [build_distributed_baseimage_aarch64]

.test_template_distributed:
  timeout: 8h
  image: $CSCS_REGISTRY_PATH/public/$ARCH/icon4py/icon4py-ci:$CI_COMMIT_SHA-$UV_PROJECT_ENVIRONMENT-$PYVERSION-mpi
  extends: [.container-runner-santis-gh200, .build_distributed_cpu]
  needs: [build_distributed_cpu]
  variables:
    SLURM_JOB_NUM_NODES: 1
    SLURM_CPU_BIND: 'verbose'
    SLURM_NTASKS: 4
    SLURM_GPUS_PER_TASK: 1
    TEST_DATA_PATH: "/icon4py/testdata"
    ICON4PY_ENABLE_GRID_DOWNLOAD: false
    ICON4PY_ENABLE_TESTDATA_DOWNLOAD: false
    CSCS_ADDITIONAL_MOUNTS: '["/capstor/store/cscs/userlab/d126/icon4py/ci/testdata_003:$TEST_DATA_PATH"]'
    # Do not use libfabric from the host system. Libfabric with slingshot
    # support is built into the container image.
    USE_MPI: NO
    # Use libfabric slingshot (cxi) provider and recommended settings from
    # https://docs.cscs.ch/software/communication/openmpi.
    SLURM_MPI_TYPE: pmix
    PMIX_MCA_psec: native
    FI_PROVIDER: cxi
    OMPI_MCA_pml: cm
    OMPI_MCA_mtl: ofi

.test_distributed_aarch64:
  stage: test
  extends: [.test_template_distributed]
  before_script:
    - cd /icon4py
    - echo "using virtual environment at ${UV_PROJECT_ENVIRONMENT}"
    - source ${UV_PROJECT_ENVIRONMENT}/bin/activate
    - echo "running with $(python --version)"
  script:
    - scripts/ci-mpi-wrapper.sh pytest -sv -k mpi_tests --with-mpi --backend=$BACKEND model/$COMPONENT
  parallel:
    matrix:
      # - COMPONENT: [atmosphere/diffusion, atmosphere/dycore, common]
      - COMPONENT: [common]
        # BACKEND: [embedded, gtfn_cpu, dace_cpu, dace_gpu]
        BACKEND: [dace_cpu, dace_gpu]
  rules:
    - if: $COMPONENT == 'atmosphere/diffusion'
      variables:
        SLURM_TIMELIMIT: '00:05:00'
    - if: $COMPONENT == 'atmosphere/dycore' && $BACKEND == 'dace_cpu'
      variables:
        SLURM_TIMELIMIT: '00:20:00'
    - if: $COMPONENT == 'atmosphere/dycore'
      variables:
        SLURM_TIMELIMIT: '00:15:00'
    - when: on_success
      variables:
        SLURM_TIMELIMIT: '00:30:00'
  artifacts:
    when: always
    paths:
      - pytest-log-rank-*.txt

test_model_distributed:
  extends: [.test_distributed_aarch64]
