# ICON4Py - ICON inspired code in Python and GT4Py
#
# Copyright (c) 2022-2024, ETH Zurich and MeteoSwiss
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause

import dataclasses
import enum
import pathlib
from collections.abc import Mapping
from typing import Final, Literal

from icon4py.model.testing import config


DEFAULT_TEST_DATA_FOLDER: Final = "testdata"


# TODO(havogt): The following are not definitions, refactor or move to a different place
def get_test_data_root_path() -> pathlib.Path:
    if config.TEST_DATA_PATH:
        return pathlib.Path(config.TEST_DATA_PATH)

    test_utils_path = pathlib.Path(__file__).parent
    model_path = test_utils_path.parent
    common_path = model_path.parent.parent.parent.parent
    return common_path.parent.joinpath(DEFAULT_TEST_DATA_FOLDER)


def serialized_data_path() -> pathlib.Path:
    return get_test_data_root_path().joinpath("ser_icondata")


def grids_path() -> pathlib.Path:
    return get_test_data_root_path().joinpath("grids")


class GridKind(enum.Enum):
    REGIONAL = "REGIONAL"
    GLOBAL = "GLOBAL"
    TORUS = "TORUS"


@dataclasses.dataclass
class Grid:
    name: str
    description: str
    kind: GridKind
    sizes: Mapping[Literal["cell", "edge", "vertex"], int]
    file_name: str | None = None
    uri: str | None = None


class Grids:
    SIMPLE: Final = Grid(
        name="<simple-grid>",
        description="Torus grid, fully defined in code (simple.py) used for testing ",
        sizes={"cell": 18, "vertex": 9, "edge": 27},
        kind=GridKind.TORUS,
        file_name=None,
        uri=None,
    )
    R02B04_GLOBAL: Final = Grid(
        name="r02b04_global",
        description="R02B04, small global grid, default grid used in ICON testing, origin of this file is unclear (source = icon-dev)",
        sizes={"cell": 20480, "vertex": 10242, "edge": 30720},
        kind=GridKind.GLOBAL,
        file_name="icon_grid_0013_R02B04_R.nc",
        uri="https://polybox.ethz.ch/index.php/s/BRiF7XrCCpGqpEF/download",
    )

    R02B07_GLOBAL: Final = Grid(
        name="r02b07_global",
        description="R02b07, large global grid, generated by MPI-M GridGenerator",
        sizes={"cell": 1310720, "vertex": 655362, "edge": 1966080},
        kind=GridKind.GLOBAL,
        file_name="icon_grid_0023_R02B07_G.nc",
        uri="https://polybox.ethz.ch/index.php/s/RMqNbaeHLD5tDd6/download",
    )
    R19_B07_MCH_LOCAL: Final = Grid(
        name="mch_opr_r19b07_icon_ch2",
        description="Grid used in the full icon-ch2 (2km resolution) operational setup of MeteoSwiss, generated by icontools (DWD)",
        sizes={"cell": 283876, "vertex": 142724, "edge": 426599},
        kind=GridKind.REGIONAL,
        file_name="icon_grid_0002_R19B07_mch.nc",
        uri="https://polybox.ethz.ch/index.php/s/tFQian4aDzTES6c/download",
    )
    MCH_OPR_R04B07_DOMAIN01: Final = Grid(
        name="mch_opr_r4b7",
        description="Grid used in the icon-ch2_small experiment (generated by IconTools (DWD) (used by MeteoSwiss for verification of icon-ch2 setup) )",
        sizes={"cell": 10700, "vertex": 5510, "edge": 16209},
        kind=GridKind.REGIONAL,
        file_name="mch_opr_r4b7_DOM01.nc",
        uri="https://polybox.ethz.ch/index.php/s/ZL7LeEDijGCSJGz/download",
    )
    MCH_OPR_R19B08_DOMAIN01: Final = Grid(
        name="mch_opr_r19b08",
        description="Grid used in some older MCH experiment, suitable for running single GPU benchmarks",
        sizes={"cell": 44528, "vertex": 22569, "edge": 67096},
        kind=GridKind.REGIONAL,
        file_name="domain1_DOM01.nc",
        uri="https://polybox.ethz.ch/index.php/s/P6XfWcYjnrsNmeX/download",
    )
    MCH_CH_R04B09_DSL: Final = Grid(
        name="mch_ch_r04b09_dsl",
        description="grid used in the mch_ch_r04b09_dsl experiment used for verification of ICON-exclaim DSL port, generated by IconTools (DWD)",
        sizes={"cell": 20896, "vertex": 10663, "edge": 31558},
        kind=GridKind.REGIONAL,
        file_name="grid.nc",
        uri="https://polybox.ethz.ch/index.php/s/hD232znfEPBh4Oh/download",
    )
    TORUS_100X116_1000M: Final = Grid(
        name="torus_100x116_res1000",
        description="Torus grid with a domain (100x116) vertices and a resolution (edge length) of 1000m, generated by MPI-M GridGenerator ",
        sizes={"cell": 23200, "vertex": 11600, "edge": 34800},
        kind=GridKind.TORUS,
        file_name=" Torus_Triangles_100x116_1000m.nc",
        uri="https://polybox.ethz.ch/index.php/s/yqvotFss9i1OKzs/download",
    )
    TORUS_50000x5000: Final = Grid(
        name="torus_50000x5000_res500",
        description="Torus grid with a resolution (edge_length) of 757m, generated by MPI-M GridGenerator",
        sizes={"cell": 1056, "vertex": 52, "edge": 1584},
        kind=GridKind.TORUS,
        file_name="Torus_Triangles_50000m_x_5000m_res500m.nc",
        uri="https://polybox.ethz.ch/index.php/s/eclzK00TM9nnLtE/download",
    )


@dataclasses.dataclass
class Experiment:
    name: str
    description: str
    grid: Grid
    num_levels: int
    partitioned_data: Mapping[int, str] | None = None


class Experiments:
    EXCLAIM_APE: Final = Experiment(
        name="exclaim_ape_R02B04",
        description="EXCLAIM Aquaplanet experiment",
        grid=Grids.R02B04_GLOBAL,
        num_levels=60,
        partitioned_data={1: "https://polybox.ethz.ch/index.php/s/2n2WpTgZFlTCTHu/download"},
    )
    MCH_CH_R04B09: Final = Experiment(
        name="mch_ch_r04b09_dsl",
        description="Regional setup used by EXCLAIM to validate the icon-exclaim.",
        grid=Grids.MCH_CH_R04B09_DSL,
        num_levels=65,
        partitioned_data={
            1: "https://polybox.ethz.ch/index.php/s/f42nsmvgOoWZPzi/download",
            2: "https://polybox.ethz.ch/index.php/s/P6F6ZbzWHI881dZ/download",
            4: "https://polybox.ethz.ch/index.php/s/NfES3j9no15A0aX/download",
        },
    )
    JW: Final = Experiment(
        name="jabw_R02B04",
        description="Jablonowski Williamson atmospheric test case",
        grid=Grids.R02B04_GLOBAL,
        num_levels=35,
        partitioned_data={1: "https://polybox.ethz.ch/index.php/s/5W3Z2K6pyo0egzo/download"},
    )
    GAUSS3D: Final = Experiment(
        name="gauss3d_torus",
        description="Gauss 3d test case",
        grid=Grids.TORUS_50000x5000,
        num_levels=35,
        partitioned_data={1: "https://polybox.ethz.ch/index.php/s/ZuqDIREPVits9r0/download"},
    )
    WEISMAN_KLEMP_TORUS: Final = Experiment(
        name="weisman_klemp_torus",
        description="Weisman-Klemp experiment on Torus Grid",
        grid=Grids.TORUS_50000x5000,
        num_levels=64,
        partitioned_data={1: "https://polybox.ethz.ch/index.php/s/ByLnyii7MMRHJbK/download"},
    )
