# ICON4Py - ICON inspired code in Python and GT4Py
#
# Copyright (c) 2022-2024, ETH Zurich and MeteoSwiss
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause

from __future__ import annotations

import dataclasses
import pathlib
from collections.abc import Mapping
from typing import TYPE_CHECKING, Final, Literal

from icon4py.model.common.grid import base, icon as icon_grid
from icon4py.model.testing import config


if TYPE_CHECKING:
    from icon4py.model.atmosphere.diffusion import diffusion
    from icon4py.model.atmosphere.dycore import solve_nonhydro as solve_nh


SERIALIZED_DATA_DIR: Final = "ser_icondata"
SERIALIZED_DATA_SUBDIR: Final = "ser_data"
GRID_DATA_DIR: Final = "grids"


def serialized_data_path() -> pathlib.Path:
    return config.TEST_DATA_PATH.joinpath(SERIALIZED_DATA_DIR)


def grids_path() -> pathlib.Path:
    return config.TEST_DATA_PATH.joinpath(GRID_DATA_DIR)


@dataclasses.dataclass
class GridDescription:
    name: str
    description: str
    shape: icon_grid.GridShape
    sizes: Mapping[Literal["cell", "edge", "vertex"], int]
    file_name: str
    uri: str


class Grids:
    R02B04_GLOBAL: Final = GridDescription(
        name="r02b04_global",
        description="R02B04, small global grid, default grid used in ICON testing, origin of this file is unclear (source = icon-dev)",
        sizes={"cell": 20480, "vertex": 10242, "edge": 30720},
        shape=icon_grid.GridShape(
            geometry_type=base.GeometryType.ICOSAHEDRON,
            subdivision=icon_grid.GridSubdivision(root=2, level=4),
        ),
        file_name="icon_grid_0013_R02B04_R.nc",
        uri="https://polybox.ethz.ch/index.php/s/BRiF7XrCCpGqpEF/download",
    )

    R02B07_GLOBAL: Final = GridDescription(
        name="r02b07_global",
        description="R02B07, large global grid, generated by MPI-M GridGenerator",
        sizes={"cell": 1310720, "vertex": 655362, "edge": 1966080},
        shape=icon_grid.GridShape(
            geometry_type=base.GeometryType.ICOSAHEDRON,
            subdivision=icon_grid.GridSubdivision(root=2, level=7),
        ),
        file_name="icon_grid_0023_R02B07_G.nc",
        uri="https://polybox.ethz.ch/index.php/s/RMqNbaeHLD5tDd6/download",
    )
    R02B06_GLOBAL: Final = GridDescription(
        name="r02b06_global",
        description="R02B06, generated by MPI-M GridGenerator",
        sizes={"cell": 327680, "vertex": 163842, "edge": 491520},
        shape=icon_grid.GridShape(
            geometry_type=base.GeometryType.ICOSAHEDRON,
            subdivision=icon_grid.GridSubdivision(root=2, level=6),
        ),
        file_name="icon_grid_0021_R02B06_G.nc",
        uri="https://polybox.ethz.ch/index.php/s/WsHr5e2MKpHkkmp/download",
    )
    R19_B07_MCH_LOCAL: Final = GridDescription(
        name="mch_opr_r19b07_icon_ch2",
        description="Grid used in the full icon-ch2 (2km resolution) operational setup of MeteoSwiss, generated by icontools (DWD)",
        sizes={"cell": 283876, "vertex": 142724, "edge": 426599},
        shape=icon_grid.GridShape(
            geometry_type=base.GeometryType.ICOSAHEDRON,
            subdivision=icon_grid.GridSubdivision(root=19, level=7),
        ),
        file_name="icon_grid_0002_R19B07_mch.nc",
        uri="https://polybox.ethz.ch/index.php/s/tFQian4aDzTES6c/download",
    )
    MCH_OPR_R04B07_DOMAIN01: Final = GridDescription(
        name="mch_opr_r4b7",
        description="Grid used in the icon-ch2_small experiment (generated by IconTools (DWD) (used by MeteoSwiss for verification of icon-ch2 setup) )",
        sizes={"cell": 10700, "vertex": 5510, "edge": 16209},
        shape=icon_grid.GridShape(
            geometry_type=base.GeometryType.ICOSAHEDRON,
            subdivision=icon_grid.GridSubdivision(root=4, level=7),
        ),
        file_name="mch_opr_r4b7_DOM01.nc",
        uri="https://polybox.ethz.ch/index.php/s/ZL7LeEDijGCSJGz/download",
    )
    MCH_OPR_R19B08_DOMAIN01: Final = GridDescription(
        name="mch_opr_r19b08",
        description="Grid used in some older MCH experiment, suitable for running single GPU benchmarks",
        sizes={"cell": 44528, "vertex": 22569, "edge": 67096},
        shape=icon_grid.GridShape(
            geometry_type=base.GeometryType.ICOSAHEDRON,
            subdivision=icon_grid.GridSubdivision(root=19, level=8),
        ),
        file_name="domain1_DOM01.nc",
        uri="https://polybox.ethz.ch/index.php/s/P6XfWcYjnrsNmeX/download",
    )
    MCH_CH_R04B09_DSL: Final = GridDescription(
        name="mch_ch_r04b09_dsl",
        description="grid used in the mch_ch_r04b09_dsl experiment used for verification of ICON-exclaim DSL port, generated by IconTools (DWD)",
        sizes={"cell": 20896, "vertex": 10663, "edge": 31558},
        shape=icon_grid.GridShape(
            geometry_type=base.GeometryType.ICOSAHEDRON,
            subdivision=icon_grid.GridSubdivision(root=4, level=9),
        ),
        file_name="grid.nc",
        uri="https://polybox.ethz.ch/index.php/s/hD232znfEPBh4Oh/download",
    )
    TORUS_100X116_1000M: Final = GridDescription(
        name="torus_100x116_res1000",
        description="Torus grid with a domain (100x116) vertices and a resolution (edge length) of 1000m, generated by MPI-M GridGenerator ",
        sizes={"cell": 23200, "vertex": 11600, "edge": 34800},
        shape=icon_grid.GridShape(geometry_type=base.GeometryType.TORUS),
        file_name="Torus_Triangles_100x116_1000m.nc",
        uri="https://polybox.ethz.ch/index.php/s/yqvotFss9i1OKzs/download",
    )
    TORUS_50000x5000: Final = GridDescription(
        name="torus_50000x5000_res500",
        description="Torus grid with a resolution (edge_length) of 757m, generated by MPI-M GridGenerator",
        sizes={"cell": 1056, "vertex": 52, "edge": 1584},
        shape=icon_grid.GridShape(geometry_type=base.GeometryType.TORUS),
        file_name="Torus_Triangles_50000m_x_5000m_res500m.nc",
        uri="https://polybox.ethz.ch/index.php/s/eclzK00TM9nnLtE/download",
    )


# Root URLs for downloading serialized data by communicator size
SERIALIZED_DATA_ROOT_URLS: Final = {
    1: "https://polybox.ethz.ch/index.php/s/KBsngNwwzRcMG5J",  # (jcanton)
    2: "https://polybox.ethz.ch/index.php/s/KfmJEEnaKCFgGSM",  # (ongchia)
    4: "https://polybox.ethz.ch/index.php/s/eLLcDtxek858ayt",  # (havogt)
}


@dataclasses.dataclass
class Experiment:
    name: str
    description: str
    grid: GridDescription
    num_levels: int
    version: int = 0


class Experiments:
    EXCLAIM_APE: Final = Experiment(
        name="exclaim_ape_R02B04",
        description="EXCLAIM Aquaplanet experiment",
        grid=Grids.R02B04_GLOBAL,
        num_levels=60,
    )
    MCH_CH_R04B09: Final = Experiment(
        name="exclaim_ch_r04b09_dsl",
        description="Regional setup used by EXCLAIM to validate the icon-exclaim.",
        grid=Grids.MCH_CH_R04B09_DSL,
        num_levels=65,
    )
    JW: Final = Experiment(
        name="exclaim_nh35_tri_jws",
        description="Jablonowski Williamson atmospheric test case",
        grid=Grids.R02B04_GLOBAL,
        num_levels=35,
    )
    GAUSS3D: Final = Experiment(
        name="exclaim_gauss3d",
        description="Gauss 3d test case",
        grid=Grids.TORUS_50000x5000,
        num_levels=35,
    )
    WEISMAN_KLEMP_TORUS: Final = Experiment(
        name="exclaim_nh_weisman_klemp",
        description="Weisman-Klemp experiment on Torus Grid",
        grid=Grids.TORUS_50000x5000,
        num_levels=64,
    )


# TODO(havogt): the following configs should be part of the serialized experiment
def construct_diffusion_config(
    experiment: Experiment, ndyn_substeps: int = 5
) -> diffusion.DiffusionConfig:
    from icon4py.model.atmosphere.diffusion import diffusion

    if experiment == Experiments.MCH_CH_R04B09:
        return diffusion.DiffusionConfig(
            diffusion_type=diffusion.DiffusionType.SMAGORINSKY_4TH_ORDER,
            hdiff_w=True,
            hdiff_vn=True,
            type_t_diffu=2,
            type_vn_diffu=1,
            hdiff_efdt_ratio=24.0,
            hdiff_w_efdt_ratio=15.0,
            smagorinski_scaling_factor=0.025,
            zdiffu_t=True,
            thslp_zdiffu=0.02,
            thhgtd_zdiffu=125.0,
            velocity_boundary_diffusion_denom=150.0,
            max_nudging_coefficient=0.375,
            n_substeps=ndyn_substeps,
            shear_type=diffusion.TurbulenceShearForcingType.VERTICAL_HORIZONTAL_OF_HORIZONTAL_VERTICAL_WIND,
        )
    elif experiment == Experiments.EXCLAIM_APE:
        return diffusion.DiffusionConfig(
            diffusion_type=diffusion.DiffusionType.SMAGORINSKY_4TH_ORDER,
            hdiff_w=True,
            hdiff_vn=True,
            zdiffu_t=False,
            type_t_diffu=2,
            type_vn_diffu=1,
            hdiff_efdt_ratio=24.0,
            smagorinski_scaling_factor=0.025,
            hdiff_temp=True,
            n_substeps=ndyn_substeps,
        )
    elif experiment == Experiments.GAUSS3D:
        return diffusion.DiffusionConfig(
            n_substeps=ndyn_substeps,
        )
    else:
        raise NotImplementedError(
            f"DiffusionConfig for experiment {experiment.name} not implemented."
        )


def construct_nonhydrostatic_config(experiment: Experiment) -> solve_nh.NonHydrostaticConfig:
    from icon4py.model.atmosphere.dycore import dycore_states, solve_nonhydro as solve_nh

    if experiment == Experiments.MCH_CH_R04B09:
        return solve_nh.NonHydrostaticConfig(
            divdamp_order=dycore_states.DivergenceDampingOrder.COMBINED,  # type: ignore[arg-type] # TODO(havogt): typing in `NonHydrostaticConfig` needs to be fixed
            iau_wgt_dyn=1.0,
            fourth_order_divdamp_factor=0.004,
            max_nudging_coefficient=0.375,
        )
    elif experiment == Experiments.EXCLAIM_APE:
        return solve_nh.NonHydrostaticConfig(
            rayleigh_coeff=0.1,
            divdamp_order=dycore_states.DivergenceDampingOrder.COMBINED,  # type: ignore[arg-type] # TODO(havogt): typing in `NonHydrostaticConfig` needs to be fixed
        )
    elif experiment == Experiments.GAUSS3D:
        return solve_nh.NonHydrostaticConfig(
            fourth_order_divdamp_factor=0.0025,
        )
    else:
        raise NotImplementedError(
            f"NonHydrostaticConfig for experiment {experiment.name} not implemented."
        )


def construct_metrics_config(experiment: Experiment) -> tuple:
    match experiment:
        case Experiments.MCH_CH_R04B09:
            lowest_layer_thickness = 20.0
            model_top_height = 23000.0
            stretch_factor = 0.65
            damping_height = 12500.0
            rayleigh_coeff = 5.0
            exner_expol = 0.333
            vwind_offctr = 0.2
            rayleigh_type = 2
        case Experiments.EXCLAIM_APE:
            lowest_layer_thickness = 50.0
            model_top_height = 75000.0
            stretch_factor = 0.9
            damping_height = 50000.0
            rayleigh_coeff = 0.1
            exner_expol = 0.3333333333333
            vwind_offctr = 0.15
            rayleigh_type = 2
        case Experiments.GAUSS3D:
            lowest_layer_thickness = 50.0
            model_top_height = 23500.0
            stretch_factor = 1.0
            damping_height = 45000.0
            rayleigh_coeff = 0.1
            exner_expol = 1.0 / 3.0
            vwind_offctr = 0.15
            rayleigh_type = 2
        case Experiments.WEISMAN_KLEMP_TORUS:
            lowest_layer_thickness = 50.0
            model_top_height = 23500.0
            stretch_factor = 1.0
            damping_height = 8000.0
            rayleigh_coeff = 0.75
            exner_expol = 0.333
            vwind_offctr = 0.15
            rayleigh_type = 2
        case _:
            raise NotImplementedError(
                f"Metrics config for experiment {experiment.name} not implemented."
            )

    return (
        lowest_layer_thickness,
        model_top_height,
        stretch_factor,
        damping_height,
        rayleigh_coeff,
        exner_expol,
        vwind_offctr,
        rayleigh_type,
    )
