extern int diffusion_run_wrapper(
    double *w, int w_size_0, int w_size_1, double *vn, int vn_size_0,
    int vn_size_1, double *exner, int exner_size_0, int exner_size_1,
    double *theta_v, int theta_v_size_0, int theta_v_size_1, double *rho,
    int rho_size_0, int rho_size_1, double *hdef_ic, int hdef_ic_size_0,
    int hdef_ic_size_1, double *div_ic, int div_ic_size_0, int div_ic_size_1,
    double *dwdx, int dwdx_size_0, int dwdx_size_1, double *dwdy,
    int dwdy_size_0, int dwdy_size_1, double dtime, int linit);
extern int diffusion_init_wrapper(
    double *vct_a, int vct_a_size_0, double *vct_b, int vct_b_size_0,
    double *theta_ref_mc, int theta_ref_mc_size_0, int theta_ref_mc_size_1,
    double *wgtfac_c, int wgtfac_c_size_0, int wgtfac_c_size_1,
    double *e_bln_c_s, int e_bln_c_s_size_0, int e_bln_c_s_size_1,
    double *geofac_div, int geofac_div_size_0, int geofac_div_size_1,
    double *geofac_grg_x, int geofac_grg_x_size_0, int geofac_grg_x_size_1,
    double *geofac_grg_y, int geofac_grg_y_size_0, int geofac_grg_y_size_1,
    double *geofac_n2s, int geofac_n2s_size_0, int geofac_n2s_size_1,
    double *nudgecoeff_e, int nudgecoeff_e_size_0, double *rbf_coeff_1,
    int rbf_coeff_1_size_0, int rbf_coeff_1_size_1, double *rbf_coeff_2,
    int rbf_coeff_2_size_0, int rbf_coeff_2_size_1, int *mask_hdiff,
    int mask_hdiff_size_0, int mask_hdiff_size_1, double *zd_diffcoef,
    int zd_diffcoef_size_0, int zd_diffcoef_size_1, int *zd_vertoffset,
    int zd_vertoffset_size_0, int zd_vertoffset_size_1,
    int zd_vertoffset_size_2, double *zd_intcoef, int zd_intcoef_size_0,
    int zd_intcoef_size_1, int zd_intcoef_size_2, int ndyn_substeps,
    double rayleigh_damping_height, int nflat_gradp, int diffusion_type,
    int hdiff_w, int hdiff_vn, int zdiffu_t, int type_t_diffu,
    int type_vn_diffu, double hdiff_efdt_ratio,
    double smagorinski_scaling_factor, int hdiff_temp, double thslp_zdiffu,
    double thhgtd_zdiffu, double denom_diffu_v, double nudge_max_coeff,
    int itype_sher, int ltkeshs, double *tangent_orientation,
    int tangent_orientation_size_0, double *inverse_primal_edge_lengths,
    int inverse_primal_edge_lengths_size_0, double *inv_dual_edge_length,
    int inv_dual_edge_length_size_0, double *inv_vert_vert_length,
    int inv_vert_vert_length_size_0, double *edge_areas, int edge_areas_size_0,
    double *f_e, int f_e_size_0, double *cell_center_lat,
    int cell_center_lat_size_0, double *cell_center_lon,
    int cell_center_lon_size_0, double *cell_areas, int cell_areas_size_0,
    double *primal_normal_vert_x, int primal_normal_vert_x_size_0,
    int primal_normal_vert_x_size_1, double *primal_normal_vert_y,
    int primal_normal_vert_y_size_0, int primal_normal_vert_y_size_1,
    double *dual_normal_vert_x, int dual_normal_vert_x_size_0,
    int dual_normal_vert_x_size_1, double *dual_normal_vert_y,
    int dual_normal_vert_y_size_0, int dual_normal_vert_y_size_1,
    double *primal_normal_cell_x, int primal_normal_cell_x_size_0,
    int primal_normal_cell_x_size_1, double *primal_normal_cell_y,
    int primal_normal_cell_y_size_0, int primal_normal_cell_y_size_1,
    double *dual_normal_cell_x, int dual_normal_cell_x_size_0,
    int dual_normal_cell_x_size_1, double *dual_normal_cell_y,
    int dual_normal_cell_y_size_0, int dual_normal_cell_y_size_1,
    double *edge_center_lat, int edge_center_lat_size_0,
    double *edge_center_lon, int edge_center_lon_size_0,
    double *primal_normal_x, int primal_normal_x_size_0,
    double *primal_normal_y, int primal_normal_y_size_0, int global_root,
    int global_level, double lowest_layer_thickness, double model_top_height,
    double stretch_factor);
extern int grid_init_diffusion_wrapper(
    int *cell_starts, int cell_starts_size_0, int *cell_ends,
    int cell_ends_size_0, int *vertex_starts, int vertex_starts_size_0,
    int *vertex_ends, int vertex_ends_size_0, int *edge_starts,
    int edge_starts_size_0, int *edge_ends, int edge_ends_size_0, int *c2e,
    int c2e_size_0, int c2e_size_1, int *e2c, int e2c_size_0, int e2c_size_1,
    int *c2e2c, int c2e2c_size_0, int c2e2c_size_1, int *e2c2e,
    int e2c2e_size_0, int e2c2e_size_1, int *e2v, int e2v_size_0,
    int e2v_size_1, int *v2e, int v2e_size_0, int v2e_size_1, int *v2c,
    int v2c_size_0, int v2c_size_1, int *e2c2v, int e2c2v_size_0,
    int e2c2v_size_1, int *c2v, int c2v_size_0, int c2v_size_1,
    int *c_owner_mask, int c_owner_mask_size_0, int *e_owner_mask,
    int e_owner_mask_size_0, int *v_owner_mask, int v_owner_mask_size_0,
    int *c_glb_index, int c_glb_index_size_0, int *e_glb_index,
    int e_glb_index_size_0, int *v_glb_index, int v_glb_index_size_0,
    int comm_id, int global_root, int global_level, int num_vertices,
    int num_cells, int num_edges, int vertical_size, int limited_area);