name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: |
            **/pyproject.toml
            uv.lock
      - name: Install all icon4py namespace packages
        run: |
          uv sync --extra all
      - name: Build documentation
        run: |
          source .venv/bin/activate
          cd model/atmosphere/dycore/docs
          make html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: model/atmosphere/dycore/docs/_build/html
