name: Deploy Documentation

on:
  push:
    branches:
      - main
    workflow_dispatch:


jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev
      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
              version: "0.6.16"
              enable-cache: true
              cache-dependency-glob: "uv.lock"
              python-version: "3.10"
      - name: Build documentation
        run: |
            cd model/atmosphere/dycore/docs/
            uv run --project ../../../../ --only-dev make html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: model/atmosphere/dycore/docs/_build/html
