name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 4: Install all icon4py namespace packages
      - name: Install all icon4py namespace packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r ./requirements-dev.txt
          python -m pip list

      # Step 5: Build documentation
      - name: Build documentation
        run: |
          cd model/atmosphere/dycore/docs
          make html

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: model/atmosphere/dycore/docs/_build/html
