name: ICON4PyTools Quality Assurance

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "tools/**"
            - "base-requirements*"
            - ".github/workflows/icon4pytools*"
    pull_request:
        branches:
            - main
        paths:
            - "tools/**"
            - "base-requirements*"
            - ".github/workflows/icon4pytools*"
        types: [opened, reopened, assigned, ready_for_review]
    pull_request_review:
        branches:
            - main
        paths:
            - "tools/**"
            - "base-requirements*"
            - ".github/workflows/icon4pytools*"
        types: [submitted]

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
                  cache: 'pip'
                  cache-dependency-path: |
                    **/pyproject.toml
                    **/base-requirements.txt
                    **/base-requirements-dev.txt
                    **/requirements.txt
                    **/requirements-dev.txt
            - name: Install dependencies
              working-directory: tools
              run: |
                  python -m pip install --upgrade pip setuptools wheel
                  python -m pip install -r ./requirements-dev.txt
                  python -m pip list
            - name: Run checks
              run: |
                  pre-commit run --config tools/.pre-commit-config.yaml --all-files
