name: ICON4Py Unit Tests
on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        types: [opened, reopened, synchronize]
jobs:
    test-tools:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11"]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install system dependencies
              run: |
                sudo apt-get update
                sudo apt-get install libboost-all-dev
            # we need to install python with setup-python action and cannot rely on the setup-uv:
            # we need to link to the python library in the CFFI test in tools and  LD_LIBRARY_PATH
            # is not set correctly in the setup-uv action
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: install uv
              uses: astral-sh/setup-uv@v5
              with:
                  version: "0.6.16"
                  enable-cache: true
                  cache-dependency-glob: "uv.lock"
            - name: run nox session - tools
              env:
                NUM_PROCESSES: auto
              shell: bash
              run: |
                uv run nox -s "test_tools-${{matrix.python-version}}(unittest)" --
