on:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: mshick/add-pr-comment@v3
        with:
          refresh-message-position: true
          message: |2

            **Mandatory Tests**

            You can test your changes on CSCS CI before merge with the `default` pipeline:

            * `cscs-ci run default`

            You can pass options to override pipeline variables, for example:

            * `cscs-ci run default;BACKENDS=gtfn_cpu;LEVELS=unit`
            * `cscs-ci run default;MODEL_SUBPACKAGES=common:driver;SESSION=model`

            **Avoid running the pipeline for all tests when you are developing.**

            All tests will be run on merge through the merge queue.

            **Optional Tests**

            To run benchmarks you can use:

            * `cscs-ci run benchmark-bencher`

            For more detailed information please look at [CI in the EXCLAIM universe](https://github.com/C2SM/icon-exclaim/wiki).
