on:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: mshick/add-pr-comment@v3
        with:
          refresh-message-position: true
          message: |2

            **Mandatory Tests**

            **Before merging, run the `merge` pipeline with `cscs-ci run merge`. Merging is blocked unless this pipeline passes.**

            When developing, You can test your changes on CSCS CI before merge with the `default` pipeline: `cscs-ci run default`. This will run a default subset of tests.

            You can pass options to override pipeline variables, for example:

            * `cscs-ci run default;BACKENDS=gtfn_cpu;LEVELS=unit`
            * `cscs-ci run default;MODEL_SUBPACKAGES=common:driver;SESSION=model`

            **Avoid running the pipeline for all tests when you are developing.**

            Available options are:
            * `SESSIONS`: `model`, `model_mpi`, or `tools` (correspond to nox sessions)
            * `MODEL_SUBSETS`: `datatest`, `basic`, or `stencils` (correspond nox session selections)
            * `MODEL_SUBPACKAGES`: subpackages for non-MPI tests (last component, e.g. `diffusion`, `standalone_driver`)
            * `MODEL_MPI_SUBPACKAGES`: subpackages for MPI tests (as above)
            * `BACKENDS`: backends
            * `GRIDS`: grids for stencil tests (`simple` or `icon_regional`)
            * `LEVELS`: testing level for non-stencil tests (`any`, `unit`, or `integration`)

            See `scripts/python/generate_ci_pipeline.py` and `noxfile.py` for available values for each option.

            **Optional Tests**

            To run benchmarks you can use:

            * `cscs-ci run benchmark-bencher`

            For more detailed information please look at [CI in the EXCLAIM universe](https://github.com/C2SM/icon-exclaim/wiki).
