name: ICON4Py Quality Assurance

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  pre-commit-icon4py-model:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        uses: ./.github/workflows/install-dependencies.yml
        with:
          python-version: "3.10"

      - name: Run checks
        run: |
          pre-commit run
